/* tslint:disable */
/* eslint-disable */
/**
 * AppLab API
 * AppLab deploys an application to Kubernetes by uploading its source.  Every JSON route answers inside a `{\"data\": ...}` envelope, except `/health`; failures answer `{\"error\": \"...\", \"retryable\": bool}`. Three routes answer `text/plain` and may stream (`x-streaming`), which a client must read incrementally rather than buffer.  This document is generated from AppLab\'s route table. Do not edit it by hand — run `make gen-openapi`.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type CreateApp201Response,
    CreateApp201ResponseFromJSON,
    CreateApp201ResponseToJSON,
} from '../models/CreateApp201Response';
import {
    type CreateAppRequest,
    CreateAppRequestFromJSON,
    CreateAppRequestToJSON,
} from '../models/CreateAppRequest';
import {
    type DeleteApp200Response,
    DeleteApp200ResponseFromJSON,
    DeleteApp200ResponseToJSON,
} from '../models/DeleteApp200Response';
import {
    type ListApps200Response,
    ListApps200ResponseFromJSON,
    ListApps200ResponseToJSON,
} from '../models/ListApps200Response';
import {
    type UpdateAppRequest,
    UpdateAppRequestFromJSON,
    UpdateAppRequestToJSON,
} from '../models/UpdateAppRequest';

export interface CreateAppOperationRequest {
    /**
     * 
     */
    createAppRequest: CreateAppRequest;
}

export interface DeleteAppRequest {
    /**
     * 
     */
    app: string;
    /**
     * Retain the git repository when the app is deleted.
     */
    keepSource?: boolean;
}

export interface GetAppRequest {
    /**
     * 
     */
    app: string;
}

export interface UpdateAppOperationRequest {
    /**
     * 
     */
    app: string;
    /**
     * 
     */
    updateAppRequest: UpdateAppRequest;
}

/**
 * 
 */
export class AppsApi extends runtime.BaseAPI {

    /**
     * Creates request options for createApp without sending the request
     */
    async createAppRequestOpts(requestParameters: CreateAppOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['createAppRequest'] == null) {
            throw new runtime.RequiredError(
                'createAppRequest',
                'Required parameter "createAppRequest" was null or undefined when calling createApp().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/apps`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateAppRequestToJSON(requestParameters['createAppRequest']),
        };
    }

    /**
     * Create an app. Body: `{id, name?, port?, replicas?, dockerfile?, domain?}`.
     * Create an app.
     */
    async createAppRaw(requestParameters: CreateAppOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CreateApp201Response>> {
        const requestOptions = await this.createAppRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CreateApp201ResponseFromJSON(jsonValue));
    }

    /**
     * Create an app. Body: `{id, name?, port?, replicas?, dockerfile?, domain?}`.
     * Create an app.
     */
    async createApp(requestParameters: CreateAppOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CreateApp201Response> {
        const response = await this.createAppRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for deleteApp without sending the request
     */
    async deleteAppRequestOpts(requestParameters: DeleteAppRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['app'] == null) {
            throw new runtime.RequiredError(
                'app',
                'Required parameter "app" was null or undefined when calling deleteApp().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['keepSource'] != null) {
            queryParameters['keep_source'] = requestParameters['keepSource'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/apps/{app}`;
        urlPath = urlPath.replace('{app}', encodeURIComponent(String(requestParameters['app'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Delete the app and everything applab recorded for it. `?keep_source=true` retains the git repository. Requires an admin key: an app key may manage its app but not destroy it.
     * Delete the app and everything applab recorded for it.
     */
    async deleteAppRaw(requestParameters: DeleteAppRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DeleteApp200Response>> {
        const requestOptions = await this.deleteAppRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DeleteApp200ResponseFromJSON(jsonValue));
    }

    /**
     * Delete the app and everything applab recorded for it. `?keep_source=true` retains the git repository. Requires an admin key: an app key may manage its app but not destroy it.
     * Delete the app and everything applab recorded for it.
     */
    async deleteApp(requestParameters: DeleteAppRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DeleteApp200Response> {
        const response = await this.deleteAppRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getApp without sending the request
     */
    async getAppRequestOpts(requestParameters: GetAppRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['app'] == null) {
            throw new runtime.RequiredError(
                'app',
                'Required parameter "app" was null or undefined when calling getApp().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/apps/{app}`;
        urlPath = urlPath.replace('{app}', encodeURIComponent(String(requestParameters['app'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * One app.
     * One app.
     */
    async getAppRaw(requestParameters: GetAppRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CreateApp201Response>> {
        const requestOptions = await this.getAppRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CreateApp201ResponseFromJSON(jsonValue));
    }

    /**
     * One app.
     * One app.
     */
    async getApp(requestParameters: GetAppRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CreateApp201Response> {
        const response = await this.getAppRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for listApps without sending the request
     */
    async listAppsRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/apps`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * List apps.
     * List apps.
     */
    async listAppsRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ListApps200Response>> {
        const requestOptions = await this.listAppsRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ListApps200ResponseFromJSON(jsonValue));
    }

    /**
     * List apps.
     * List apps.
     */
    async listApps(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ListApps200Response> {
        const response = await this.listAppsRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for updateApp without sending the request
     */
    async updateAppRequestOpts(requestParameters: UpdateAppOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['app'] == null) {
            throw new runtime.RequiredError(
                'app',
                'Required parameter "app" was null or undefined when calling updateApp().'
            );
        }

        if (requestParameters['updateAppRequest'] == null) {
            throw new runtime.RequiredError(
                'updateAppRequest',
                'Required parameter "updateAppRequest" was null or undefined when calling updateApp().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/apps/{app}`;
        urlPath = urlPath.replace('{app}', encodeURIComponent(String(requestParameters['app'])));

        return {
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: UpdateAppRequestToJSON(requestParameters['updateAppRequest']),
        };
    }

    /**
     * Change an app\'s settings: `{name?, port?, replicas?, dockerfile?, domain?, auto_deploy?, branch?, resources?}`. Fields omitted are left alone; a resource field set to an empty string returns it to this deployment\'s default from `deploy.appResources`. Changing resources does not redeploy — the app\'s next deploy applies them.
     * Change an app\'s settings: `{name?, port?, replicas?, dockerfile?, domain?, auto_deploy?, branch?, resources?}`.
     */
    async updateAppRaw(requestParameters: UpdateAppOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CreateApp201Response>> {
        const requestOptions = await this.updateAppRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CreateApp201ResponseFromJSON(jsonValue));
    }

    /**
     * Change an app\'s settings: `{name?, port?, replicas?, dockerfile?, domain?, auto_deploy?, branch?, resources?}`. Fields omitted are left alone; a resource field set to an empty string returns it to this deployment\'s default from `deploy.appResources`. Changing resources does not redeploy — the app\'s next deploy applies them.
     * Change an app\'s settings: `{name?, port?, replicas?, dockerfile?, domain?, auto_deploy?, branch?, resources?}`.
     */
    async updateApp(requestParameters: UpdateAppOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CreateApp201Response> {
        const response = await this.updateAppRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
