/* tslint:disable */
/* eslint-disable */
/**
 * AppLab API
 * AppLab deploys an application to Kubernetes by uploading its source.  Every JSON route answers inside a `{\"data\": ...}` envelope, except `/health`; failures answer `{\"error\": \"...\", \"retryable\": bool}`. Three routes answer `text/plain` and may stream (`x-streaming`), which a client must read incrementally rather than buffer.  This document is generated from AppLab\'s route table. Do not edit it by hand — run `make gen-openapi`.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type GetAppUsage200Response,
    GetAppUsage200ResponseFromJSON,
    GetAppUsage200ResponseToJSON,
} from '../models/GetAppUsage200Response';
import {
    type GetOverview200Response,
    GetOverview200ResponseFromJSON,
    GetOverview200ResponseToJSON,
} from '../models/GetOverview200Response';
import {
    type ListAppEvents200Response,
    ListAppEvents200ResponseFromJSON,
    ListAppEvents200ResponseToJSON,
} from '../models/ListAppEvents200Response';
import {
    type ListAppPods200Response,
    ListAppPods200ResponseFromJSON,
    ListAppPods200ResponseToJSON,
} from '../models/ListAppPods200Response';

export interface ListSelfEventsRequest {
    /**
     * Maximum number of items to return.
     */
    limit?: number;
}

export interface ListSelfPodsRequest {
    /**
     * Maximum number of items to return.
     */
    limit?: number;
}

export interface StreamSelfLogsRequest {
    /**
     * Read one pod's log by name.
     */
    pod?: string;
    /**
     * Read one container's log within the pod.
     */
    container?: string;
    /**
     * Number of lines from the end to return.
     */
    tail?: number;
    /**
     * Read the previous container instance, where a crash loop's reason is written.
     */
    previous?: boolean;
    /**
     * Only lines newer than this duration or timestamp.
     */
    since?: string;
    /**
     * Keep the connection open and stream lines as they arrive rather than returning what exists now. Read the body incrementally; the response may never end.
     */
    follow?: boolean;
}

/**
 * 
 */
export class PlatformApi extends runtime.BaseAPI {

    /**
     * Creates request options for getOverview without sending the request
     */
    async getOverviewRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/overview`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * The platform at a glance: app counts by status, build counts and the most recent builds across every app, whether the cluster is configured and reachable, and this deployment\'s self-description. Counts exclude deleted apps.
     * The platform at a glance: app counts by status, build counts and the most recent builds across every app, whether the cluster is configured and reachable, and this deployment\'s self-description.
     */
    async getOverviewRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetOverview200Response>> {
        const requestOptions = await this.getOverviewRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GetOverview200ResponseFromJSON(jsonValue));
    }

    /**
     * The platform at a glance: app counts by status, build counts and the most recent builds across every app, whether the cluster is configured and reachable, and this deployment\'s self-description. Counts exclude deleted apps.
     * The platform at a glance: app counts by status, build counts and the most recent builds across every app, whether the cluster is configured and reachable, and this deployment\'s self-description.
     */
    async getOverview(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetOverview200Response> {
        const response = await this.getOverviewRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getSelfUsage without sending the request
     */
    async getSelfUsageRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/platform/resources`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * CPU and memory for each of AppLab\'s own pods, keyed by pod name, with `available` saying whether the cluster reports metrics at all. Admin key only. On a cluster without metrics-server `available` is false and the pods map is empty — a reading that could not be taken, which is not the same as an idle deployment.
     * CPU and memory for each of AppLab\'s own pods, keyed by pod name, with `available` saying whether the cluster reports metrics at all.
     */
    async getSelfUsageRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetAppUsage200Response>> {
        const requestOptions = await this.getSelfUsageRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GetAppUsage200ResponseFromJSON(jsonValue));
    }

    /**
     * CPU and memory for each of AppLab\'s own pods, keyed by pod name, with `available` saying whether the cluster reports metrics at all. Admin key only. On a cluster without metrics-server `available` is false and the pods map is empty — a reading that could not be taken, which is not the same as an idle deployment.
     * CPU and memory for each of AppLab\'s own pods, keyed by pod name, with `available` saying whether the cluster reports metrics at all.
     */
    async getSelfUsage(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetAppUsage200Response> {
        const response = await this.getSelfUsageRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for listSelfEvents without sending the request
     */
    async listSelfEventsRequestOpts(requestParameters: ListSelfEventsRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/platform/events`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Kubernetes events concerning AppLab\'s own objects, warnings first, with `count` and `warnings`. `?limit=` (default 50, max 500). Admin key only.
     * Kubernetes events concerning AppLab\'s own objects, warnings first, with `count` and `warnings`.
     */
    async listSelfEventsRaw(requestParameters: ListSelfEventsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ListAppEvents200Response>> {
        const requestOptions = await this.listSelfEventsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ListAppEvents200ResponseFromJSON(jsonValue));
    }

    /**
     * Kubernetes events concerning AppLab\'s own objects, warnings first, with `count` and `warnings`. `?limit=` (default 50, max 500). Admin key only.
     * Kubernetes events concerning AppLab\'s own objects, warnings first, with `count` and `warnings`.
     */
    async listSelfEvents(requestParameters: ListSelfEventsRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ListAppEvents200Response> {
        const response = await this.listSelfEventsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for listSelfPods without sending the request
     */
    async listSelfPodsRequestOpts(requestParameters: ListSelfPodsRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/platform/pods`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * AppLab\'s own pods, newest first — the deployment that serves this API, not the apps it manages. `?limit=` (default 100). Admin key only: an app key reaches one app and this is not it.
     * AppLab\'s own pods, newest first — the deployment that serves this API, not the apps it manages.
     */
    async listSelfPodsRaw(requestParameters: ListSelfPodsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ListAppPods200Response>> {
        const requestOptions = await this.listSelfPodsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ListAppPods200ResponseFromJSON(jsonValue));
    }

    /**
     * AppLab\'s own pods, newest first — the deployment that serves this API, not the apps it manages. `?limit=` (default 100). Admin key only: an app key reaches one app and this is not it.
     * AppLab\'s own pods, newest first — the deployment that serves this API, not the apps it manages.
     */
    async listSelfPods(requestParameters: ListSelfPodsRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ListAppPods200Response> {
        const response = await this.listSelfPodsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for streamSelfLogs without sending the request
     */
    async streamSelfLogsRequestOpts(requestParameters: StreamSelfLogsRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['pod'] != null) {
            queryParameters['pod'] = requestParameters['pod'];
        }

        if (requestParameters['container'] != null) {
            queryParameters['container'] = requestParameters['container'];
        }

        if (requestParameters['tail'] != null) {
            queryParameters['tail'] = requestParameters['tail'];
        }

        if (requestParameters['previous'] != null) {
            queryParameters['previous'] = requestParameters['previous'];
        }

        if (requestParameters['since'] != null) {
            queryParameters['since'] = requestParameters['since'];
        }

        if (requestParameters['follow'] != null) {
            queryParameters['follow'] = requestParameters['follow'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/platform/logs`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * AppLab\'s own log as `text/plain`, following by default; `?follow=false` returns what exists and closes. `?pod=` and `?container=` narrow it (default: the newest AppLab pod). `?previous=true` reads the previous container instance, which is where a crash loop\'s reason is written. `?tail=` (default 500, max 10000), `?since=` a duration such as `5m`. Admin key only.
     * AppLab\'s own log as `text/plain`, following by default; `?follow=false` returns what exists and closes.
     */
    async streamSelfLogsRaw(requestParameters: StreamSelfLogsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<string>> {
        const requestOptions = await this.streamSelfLogsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<string>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * AppLab\'s own log as `text/plain`, following by default; `?follow=false` returns what exists and closes. `?pod=` and `?container=` narrow it (default: the newest AppLab pod). `?previous=true` reads the previous container instance, which is where a crash loop\'s reason is written. `?tail=` (default 500, max 10000), `?since=` a duration such as `5m`. Admin key only.
     * AppLab\'s own log as `text/plain`, following by default; `?follow=false` returns what exists and closes.
     */
    async streamSelfLogs(requestParameters: StreamSelfLogsRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<string> {
        const response = await this.streamSelfLogsRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
