/* tslint:disable */
/* eslint-disable */
/**
 * AppLab API
 * AppLab deploys an application to Kubernetes by uploading its source.  Every JSON route answers inside a `{\"data\": ...}` envelope, except `/health`; failures answer `{\"error\": \"...\", \"retryable\": bool}`. Three routes answer `text/plain` and may stream (`x-streaming`), which a client must read incrementally rather than buffer.  This document is generated from AppLab\'s route table. Do not edit it by hand — run `make gen-openapi`.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type CreateApp201Response,
    CreateApp201ResponseFromJSON,
    CreateApp201ResponseToJSON,
} from '../models/CreateApp201Response';
import {
    type CreateAppRequest,
    CreateAppRequestFromJSON,
    CreateAppRequestToJSON,
} from '../models/CreateAppRequest';
import {
    type DeleteApp200Response,
    DeleteApp200ResponseFromJSON,
    DeleteApp200ResponseToJSON,
} from '../models/DeleteApp200Response';
import {
    type ListApps200Response,
    ListApps200ResponseFromJSON,
    ListApps200ResponseToJSON,
} from '../models/ListApps200Response';
import {
    type ListServers200Response,
    ListServers200ResponseFromJSON,
    ListServers200ResponseToJSON,
} from '../models/ListServers200Response';
import {
    type RegisterServer201Response,
    RegisterServer201ResponseFromJSON,
    RegisterServer201ResponseToJSON,
} from '../models/RegisterServer201Response';
import {
    type RegisterServerRequest,
    RegisterServerRequestFromJSON,
    RegisterServerRequestToJSON,
} from '../models/RegisterServerRequest';
import {
    type RemoveServer200Response,
    RemoveServer200ResponseFromJSON,
    RemoveServer200ResponseToJSON,
} from '../models/RemoveServer200Response';

export interface CreateServerAppRequest {
    /**
     * 
     */
    server: string;
    /**
     * 
     */
    createAppRequest: CreateAppRequest;
}

export interface DeleteServerAppRequest {
    /**
     * 
     */
    server: string;
    /**
     * 
     */
    app: string;
    /**
     * Retain the git repository when the app is deleted.
     */
    keepSource?: boolean;
}

export interface GetServerRequest {
    /**
     * 
     */
    server: string;
}

export interface GetServerAppRequest {
    /**
     * 
     */
    server: string;
    /**
     * 
     */
    app: string;
}

export interface ListServerAppsRequest {
    /**
     * 
     */
    server: string;
}

export interface RegisterServerOperationRequest {
    /**
     * 
     */
    registerServerRequest: RegisterServerRequest;
}

export interface RemoveServerRequest {
    /**
     * 
     */
    server: string;
}

/**
 * 
 */
export class ServersApi extends runtime.BaseAPI {

    /**
     * Creates request options for createServerApp without sending the request
     */
    async createServerAppRequestOpts(requestParameters: CreateServerAppRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['server'] == null) {
            throw new runtime.RequiredError(
                'server',
                'Required parameter "server" was null or undefined when calling createServerApp().'
            );
        }

        if (requestParameters['createAppRequest'] == null) {
            throw new runtime.RequiredError(
                'createAppRequest',
                'Required parameter "createAppRequest" was null or undefined when calling createServerApp().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/servers/{server}/apps`;
        urlPath = urlPath.replace('{server}', encodeURIComponent(String(requestParameters['server'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateAppRequestToJSON(requestParameters['createAppRequest']),
        };
    }

    /**
     * Create an app on one server. Body as `POST /api/v1/apps`. On `local` this is the same call. On a remote the response is relayed whole, including the new app\'s key — the one moment it is handed out.
     * Create an app on one server.
     */
    async createServerAppRaw(requestParameters: CreateServerAppRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CreateApp201Response>> {
        const requestOptions = await this.createServerAppRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CreateApp201ResponseFromJSON(jsonValue));
    }

    /**
     * Create an app on one server. Body as `POST /api/v1/apps`. On `local` this is the same call. On a remote the response is relayed whole, including the new app\'s key — the one moment it is handed out.
     * Create an app on one server.
     */
    async createServerApp(requestParameters: CreateServerAppRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CreateApp201Response> {
        const response = await this.createServerAppRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for deleteServerApp without sending the request
     */
    async deleteServerAppRequestOpts(requestParameters: DeleteServerAppRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['server'] == null) {
            throw new runtime.RequiredError(
                'server',
                'Required parameter "server" was null or undefined when calling deleteServerApp().'
            );
        }

        if (requestParameters['app'] == null) {
            throw new runtime.RequiredError(
                'app',
                'Required parameter "app" was null or undefined when calling deleteServerApp().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['keepSource'] != null) {
            queryParameters['keep_source'] = requestParameters['keepSource'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/servers/{server}/apps/{app}`;
        urlPath = urlPath.replace('{server}', encodeURIComponent(String(requestParameters['server'])));
        urlPath = urlPath.replace('{app}', encodeURIComponent(String(requestParameters['app'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Delete an app on one server. `?keep_source=true` is passed through.
     * Delete an app on one server.
     */
    async deleteServerAppRaw(requestParameters: DeleteServerAppRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DeleteApp200Response>> {
        const requestOptions = await this.deleteServerAppRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DeleteApp200ResponseFromJSON(jsonValue));
    }

    /**
     * Delete an app on one server. `?keep_source=true` is passed through.
     * Delete an app on one server.
     */
    async deleteServerApp(requestParameters: DeleteServerAppRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DeleteApp200Response> {
        const response = await this.deleteServerAppRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getServer without sending the request
     */
    async getServerRequestOpts(requestParameters: GetServerRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['server'] == null) {
            throw new runtime.RequiredError(
                'server',
                'Required parameter "server" was null or undefined when calling getServer().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/servers/{server}`;
        urlPath = urlPath.replace('{server}', encodeURIComponent(String(requestParameters['server'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * One server, without its key. `local` reports this deployment.
     * One server, without its key.
     */
    async getServerRaw(requestParameters: GetServerRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RegisterServer201Response>> {
        const requestOptions = await this.getServerRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => RegisterServer201ResponseFromJSON(jsonValue));
    }

    /**
     * One server, without its key. `local` reports this deployment.
     * One server, without its key.
     */
    async getServer(requestParameters: GetServerRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RegisterServer201Response> {
        const response = await this.getServerRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getServerApp without sending the request
     */
    async getServerAppRequestOpts(requestParameters: GetServerAppRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['server'] == null) {
            throw new runtime.RequiredError(
                'server',
                'Required parameter "server" was null or undefined when calling getServerApp().'
            );
        }

        if (requestParameters['app'] == null) {
            throw new runtime.RequiredError(
                'app',
                'Required parameter "app" was null or undefined when calling getServerApp().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/servers/{server}/apps/{app}`;
        urlPath = urlPath.replace('{server}', encodeURIComponent(String(requestParameters['server'])));
        urlPath = urlPath.replace('{app}', encodeURIComponent(String(requestParameters['app'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * One app on one server.
     * One app on one server.
     */
    async getServerAppRaw(requestParameters: GetServerAppRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CreateApp201Response>> {
        const requestOptions = await this.getServerAppRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CreateApp201ResponseFromJSON(jsonValue));
    }

    /**
     * One app on one server.
     * One app on one server.
     */
    async getServerApp(requestParameters: GetServerAppRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CreateApp201Response> {
        const response = await this.getServerAppRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for listServerApps without sending the request
     */
    async listServerAppsRequestOpts(requestParameters: ListServerAppsRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['server'] == null) {
            throw new runtime.RequiredError(
                'server',
                'Required parameter "server" was null or undefined when calling listServerApps().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/servers/{server}/apps`;
        urlPath = urlPath.replace('{server}', encodeURIComponent(String(requestParameters['server'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * List the apps on one server. On `local` this answers exactly what `GET /api/v1/apps` does; on a remote it relays that remote\'s list.
     * List the apps on one server.
     */
    async listServerAppsRaw(requestParameters: ListServerAppsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ListApps200Response>> {
        const requestOptions = await this.listServerAppsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ListApps200ResponseFromJSON(jsonValue));
    }

    /**
     * List the apps on one server. On `local` this answers exactly what `GET /api/v1/apps` does; on a remote it relays that remote\'s list.
     * List the apps on one server.
     */
    async listServerApps(requestParameters: ListServerAppsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ListApps200Response> {
        const response = await this.listServerAppsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for listServers without sending the request
     */
    async listServersRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/servers`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Every AppLab this deployment can manage: the built-in `local` entry first — this deployment itself — then each registered remote. The key of a remote is never returned.
     * Every AppLab this deployment can manage: the built-in `local` entry first — this deployment itself — then each registered remote.
     */
    async listServersRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ListServers200Response>> {
        const requestOptions = await this.listServersRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ListServers200ResponseFromJSON(jsonValue));
    }

    /**
     * Every AppLab this deployment can manage: the built-in `local` entry first — this deployment itself — then each registered remote. The key of a remote is never returned.
     * Every AppLab this deployment can manage: the built-in `local` entry first — this deployment itself — then each registered remote.
     */
    async listServers(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ListServers200Response> {
        const response = await this.listServersRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for registerServer without sending the request
     */
    async registerServerRequestOpts(requestParameters: RegisterServerOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['registerServerRequest'] == null) {
            throw new runtime.RequiredError(
                'registerServerRequest',
                'Required parameter "registerServerRequest" was null or undefined when calling registerServer().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/servers`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: RegisterServerRequestToJSON(requestParameters['registerServerRequest']),
        };
    }

    /**
     * Register a remote AppLab. Body: `{id, url, key, name?}`. The address and the key are checked against the remote before anything is stored, so a wrong address or a key that is not an admin key is a 400 here rather than a failure later. `url` must include any path prefix the remote is served under. 501 when this deployment has no cluster, where registrations are kept.
     * Register a remote AppLab.
     */
    async registerServerRaw(requestParameters: RegisterServerOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RegisterServer201Response>> {
        const requestOptions = await this.registerServerRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => RegisterServer201ResponseFromJSON(jsonValue));
    }

    /**
     * Register a remote AppLab. Body: `{id, url, key, name?}`. The address and the key are checked against the remote before anything is stored, so a wrong address or a key that is not an admin key is a 400 here rather than a failure later. `url` must include any path prefix the remote is served under. 501 when this deployment has no cluster, where registrations are kept.
     * Register a remote AppLab.
     */
    async registerServer(requestParameters: RegisterServerOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RegisterServer201Response> {
        const response = await this.registerServerRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for removeServer without sending the request
     */
    async removeServerRequestOpts(requestParameters: RemoveServerRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['server'] == null) {
            throw new runtime.RequiredError(
                'server',
                'Required parameter "server" was null or undefined when calling removeServer().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/servers/{server}`;
        urlPath = urlPath.replace('{server}', encodeURIComponent(String(requestParameters['server'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Forget a registration. The remote\'s apps are untouched, and the remote need not be reachable. `local` cannot be removed.
     * Forget a registration.
     */
    async removeServerRaw(requestParameters: RemoveServerRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RemoveServer200Response>> {
        const requestOptions = await this.removeServerRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => RemoveServer200ResponseFromJSON(jsonValue));
    }

    /**
     * Forget a registration. The remote\'s apps are untouched, and the remote need not be reachable. `local` cannot be removed.
     * Forget a registration.
     */
    async removeServer(requestParameters: RemoveServerRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RemoveServer200Response> {
        const response = await this.removeServerRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
