/* tslint:disable */
/* eslint-disable */
/**
 * AppLab API
 * AppLab deploys an application to Kubernetes by uploading its source.  Every JSON route answers inside a `{\"data\": ...}` envelope, except `/health`; failures answer `{\"error\": \"...\", \"retryable\": bool}`. Three routes answer `text/plain` and may stream (`x-streaming`), which a client must read incrementally rather than buffer.  This document is generated from AppLab\'s route table. Do not edit it by hand — run `make gen-openapi`.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type ChunkedUploadStartRequest,
    ChunkedUploadStartRequestFromJSON,
    ChunkedUploadStartRequestToJSON,
} from '../models/ChunkedUploadStartRequest';
import {
    type GetCommit200Response,
    GetCommit200ResponseFromJSON,
    GetCommit200ResponseToJSON,
} from '../models/GetCommit200Response';
import {
    type ListBranches200Response,
    ListBranches200ResponseFromJSON,
    ListBranches200ResponseToJSON,
} from '../models/ListBranches200Response';
import {
    type ListCommits200Response,
    ListCommits200ResponseFromJSON,
    ListCommits200ResponseToJSON,
} from '../models/ListCommits200Response';
import {
    type StartChunkedUpload201Response,
    StartChunkedUpload201ResponseFromJSON,
    StartChunkedUpload201ResponseToJSON,
} from '../models/StartChunkedUpload201Response';
import {
    type SwitchBranch200Response,
    SwitchBranch200ResponseFromJSON,
    SwitchBranch200ResponseToJSON,
} from '../models/SwitchBranch200Response';
import {
    type SwitchBranchRequest,
    SwitchBranchRequestFromJSON,
    SwitchBranchRequestToJSON,
} from '../models/SwitchBranchRequest';
import {
    type UploadSource200Response,
    UploadSource200ResponseFromJSON,
    UploadSource200ResponseToJSON,
} from '../models/UploadSource200Response';
import {
    type UploadSourcePart200Response,
    UploadSourcePart200ResponseFromJSON,
    UploadSourcePart200ResponseToJSON,
} from '../models/UploadSourcePart200Response';

export interface CompleteChunkedUploadRequest {
    /**
     * 
     */
    app: string;
    /**
     * 
     */
    upload: string;
    /**
     * Commit message, overriding the one given when the upload started.
     */
    message?: string;
    /**
     * Branch to commit to.
     */
    branch?: string;
    /**
     * Build and deploy after committing. Defaults to true; send false to upload without shipping.
     */
    publish?: boolean;
}

export interface GetCommitRequest {
    /**
     * 
     */
    app: string;
    /**
     * 
     */
    sha: string;
}

export interface ListBranchesRequest {
    /**
     * 
     */
    app: string;
}

export interface ListCommitsRequest {
    /**
     * 
     */
    app: string;
    /**
     * Maximum number of items to return.
     */
    limit?: number;
    /**
     * Read another branch's history.
     */
    branch?: string;
}

export interface StartChunkedUploadRequest {
    /**
     * 
     */
    app: string;
    /**
     * 
     */
    chunkedUploadStartRequest: ChunkedUploadStartRequest;
}

export interface SwitchBranchOperationRequest {
    /**
     * 
     */
    app: string;
    /**
     * 
     */
    switchBranchRequest: SwitchBranchRequest;
}

export interface UploadSourceRequest {
    /**
     * 
     */
    app: string;
    /**
     * 
     */
    body: Blob;
    /**
     * Commit message for the upload.
     */
    message?: string;
    /**
     * Parent commit to upload on top of (default: the branch tip).
     */
    parent?: string;
    /**
     * Branch to commit to (default: the app's active branch).
     */
    branch?: string;
    /**
     * Build and deploy after committing. Defaults to true; send false to upload without shipping.
     */
    publish?: boolean;
}

export interface UploadSourcePartRequest {
    /**
     * 
     */
    app: string;
    /**
     * 
     */
    upload: string;
    /**
     * 
     */
    index: number;
    /**
     * 
     */
    body: Blob;
}

/**
 * 
 */
export class SourceApi extends runtime.BaseAPI {

    /**
     * Creates request options for completeChunkedUpload without sending the request
     */
    async completeChunkedUploadRequestOpts(requestParameters: CompleteChunkedUploadRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['app'] == null) {
            throw new runtime.RequiredError(
                'app',
                'Required parameter "app" was null or undefined when calling completeChunkedUpload().'
            );
        }

        if (requestParameters['upload'] == null) {
            throw new runtime.RequiredError(
                'upload',
                'Required parameter "upload" was null or undefined when calling completeChunkedUpload().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['message'] != null) {
            queryParameters['message'] = requestParameters['message'];
        }

        if (requestParameters['branch'] != null) {
            queryParameters['branch'] = requestParameters['branch'];
        }

        if (requestParameters['publish'] != null) {
            queryParameters['publish'] = requestParameters['publish'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/apps/{app}/source/uploads/{upload}/complete`;
        urlPath = urlPath.replace('{app}', encodeURIComponent(String(requestParameters['app'])));
        urlPath = urlPath.replace('{upload}', encodeURIComponent(String(requestParameters['upload'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Assemble every part and commit the result. Fails if any part is missing.
     * Assemble every part and commit the result.
     */
    async completeChunkedUploadRaw(requestParameters: CompleteChunkedUploadRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<UploadSource200Response>> {
        const requestOptions = await this.completeChunkedUploadRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => UploadSource200ResponseFromJSON(jsonValue));
    }

    /**
     * Assemble every part and commit the result. Fails if any part is missing.
     * Assemble every part and commit the result.
     */
    async completeChunkedUpload(requestParameters: CompleteChunkedUploadRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<UploadSource200Response> {
        const response = await this.completeChunkedUploadRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getCommit without sending the request
     */
    async getCommitRequestOpts(requestParameters: GetCommitRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['app'] == null) {
            throw new runtime.RequiredError(
                'app',
                'Required parameter "app" was null or undefined when calling getCommit().'
            );
        }

        if (requestParameters['sha'] == null) {
            throw new runtime.RequiredError(
                'sha',
                'Required parameter "sha" was null or undefined when calling getCommit().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/apps/{app}/commits/{sha}`;
        urlPath = urlPath.replace('{app}', encodeURIComponent(String(requestParameters['app'])));
        urlPath = urlPath.replace('{sha}', encodeURIComponent(String(requestParameters['sha'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * One commit. `{sha}` may be an abbreviated id.
     * One commit.
     */
    async getCommitRaw(requestParameters: GetCommitRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetCommit200Response>> {
        const requestOptions = await this.getCommitRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GetCommit200ResponseFromJSON(jsonValue));
    }

    /**
     * One commit. `{sha}` may be an abbreviated id.
     * One commit.
     */
    async getCommit(requestParameters: GetCommitRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetCommit200Response> {
        const response = await this.getCommitRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for listBranches without sending the request
     */
    async listBranchesRequestOpts(requestParameters: ListBranchesRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['app'] == null) {
            throw new runtime.RequiredError(
                'app',
                'Required parameter "app" was null or undefined when calling listBranches().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/apps/{app}/branches`;
        urlPath = urlPath.replace('{app}', encodeURIComponent(String(requestParameters['app'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * The branches this app has source for, and which one is active. A branch is created by pushing to it, so this is what the app has been pushed to.
     * The branches this app has source for, and which one is active.
     */
    async listBranchesRaw(requestParameters: ListBranchesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ListBranches200Response>> {
        const requestOptions = await this.listBranchesRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ListBranches200ResponseFromJSON(jsonValue));
    }

    /**
     * The branches this app has source for, and which one is active. A branch is created by pushing to it, so this is what the app has been pushed to.
     * The branches this app has source for, and which one is active.
     */
    async listBranches(requestParameters: ListBranchesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ListBranches200Response> {
        const response = await this.listBranchesRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for listCommits without sending the request
     */
    async listCommitsRequestOpts(requestParameters: ListCommitsRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['app'] == null) {
            throw new runtime.RequiredError(
                'app',
                'Required parameter "app" was null or undefined when calling listCommits().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['branch'] != null) {
            queryParameters['branch'] = requestParameters['branch'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/apps/{app}/commits`;
        urlPath = urlPath.replace('{app}', encodeURIComponent(String(requestParameters['app'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * An app\'s commit history, newest first, with the current tip. `?limit=` (default 50). `?branch=` reads another branch\'s history.
     * An app\'s commit history, newest first, with the current tip.
     */
    async listCommitsRaw(requestParameters: ListCommitsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ListCommits200Response>> {
        const requestOptions = await this.listCommitsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ListCommits200ResponseFromJSON(jsonValue));
    }

    /**
     * An app\'s commit history, newest first, with the current tip. `?limit=` (default 50). `?branch=` reads another branch\'s history.
     * An app\'s commit history, newest first, with the current tip.
     */
    async listCommits(requestParameters: ListCommitsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ListCommits200Response> {
        const response = await this.listCommitsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for startChunkedUpload without sending the request
     */
    async startChunkedUploadRequestOpts(requestParameters: StartChunkedUploadRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['app'] == null) {
            throw new runtime.RequiredError(
                'app',
                'Required parameter "app" was null or undefined when calling startChunkedUpload().'
            );
        }

        if (requestParameters['chunkedUploadStartRequest'] == null) {
            throw new runtime.RequiredError(
                'chunkedUploadStartRequest',
                'Required parameter "chunkedUploadStartRequest" was null or undefined when calling startChunkedUpload().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/apps/{app}/source/uploads`;
        urlPath = urlPath.replace('{app}', encodeURIComponent(String(requestParameters['app'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ChunkedUploadStartRequestToJSON(requestParameters['chunkedUploadStartRequest']),
        };
    }

    /**
     * Begin a chunked upload for source too large for one request. Body: `{total, chunk_size, message?}`. Returns an `upload_id`.
     * Begin a chunked upload for source too large for one request.
     */
    async startChunkedUploadRaw(requestParameters: StartChunkedUploadRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<StartChunkedUpload201Response>> {
        const requestOptions = await this.startChunkedUploadRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => StartChunkedUpload201ResponseFromJSON(jsonValue));
    }

    /**
     * Begin a chunked upload for source too large for one request. Body: `{total, chunk_size, message?}`. Returns an `upload_id`.
     * Begin a chunked upload for source too large for one request.
     */
    async startChunkedUpload(requestParameters: StartChunkedUploadRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<StartChunkedUpload201Response> {
        const response = await this.startChunkedUploadRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for switchBranch without sending the request
     */
    async switchBranchRequestOpts(requestParameters: SwitchBranchOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['app'] == null) {
            throw new runtime.RequiredError(
                'app',
                'Required parameter "app" was null or undefined when calling switchBranch().'
            );
        }

        if (requestParameters['switchBranchRequest'] == null) {
            throw new runtime.RequiredError(
                'switchBranchRequest',
                'Required parameter "switchBranchRequest" was null or undefined when calling switchBranch().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/apps/{app}/branch`;
        urlPath = urlPath.replace('{app}', encodeURIComponent(String(requestParameters['app'])));

        return {
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: SwitchBranchRequestToJSON(requestParameters['switchBranchRequest']),
        };
    }

    /**
     * Make a branch active and deploy it. Body: `{\"branch\":\"dev\"}`. The branch must already have been pushed to. This replaces what is running: one app runs one branch.
     * Make a branch active and deploy it.
     */
    async switchBranchRaw(requestParameters: SwitchBranchOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SwitchBranch200Response>> {
        const requestOptions = await this.switchBranchRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SwitchBranch200ResponseFromJSON(jsonValue));
    }

    /**
     * Make a branch active and deploy it. Body: `{\"branch\":\"dev\"}`. The branch must already have been pushed to. This replaces what is running: one app runs one branch.
     * Make a branch active and deploy it.
     */
    async switchBranch(requestParameters: SwitchBranchOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SwitchBranch200Response> {
        const response = await this.switchBranchRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for uploadSource without sending the request
     */
    async uploadSourceRequestOpts(requestParameters: UploadSourceRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['app'] == null) {
            throw new runtime.RequiredError(
                'app',
                'Required parameter "app" was null or undefined when calling uploadSource().'
            );
        }

        if (requestParameters['body'] == null) {
            throw new runtime.RequiredError(
                'body',
                'Required parameter "body" was null or undefined when calling uploadSource().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['message'] != null) {
            queryParameters['message'] = requestParameters['message'];
        }

        if (requestParameters['parent'] != null) {
            queryParameters['parent'] = requestParameters['parent'];
        }

        if (requestParameters['branch'] != null) {
            queryParameters['branch'] = requestParameters['branch'];
        }

        if (requestParameters['publish'] != null) {
            queryParameters['publish'] = requestParameters['publish'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/octet-stream';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/apps/{app}/source`;
        urlPath = urlPath.replace('{app}', encodeURIComponent(String(requestParameters['app'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['body'] as any,
        };
    }

    /**
     * Upload source as a tar or tar.gz and commit it. This is the main way to push code. Send the archive as the raw request body (`--data-binary @-`), or as `multipart/form-data` with a `file` field. `?message=` sets the commit message; `?parent=<sha>` commits onto a chosen commit instead of the current tip; `?branch=` commits to another branch (default: the app\'s active one, and a branch that does not exist yet is created — see `GET /api/v1/apps/{app}/branches`). A single wrapping directory is stripped, so `tar czf - myproject` lands with its contents at the root.
     * Upload source as a tar or tar.gz and commit it.
     */
    async uploadSourceRaw(requestParameters: UploadSourceRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<UploadSource200Response>> {
        const requestOptions = await this.uploadSourceRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => UploadSource200ResponseFromJSON(jsonValue));
    }

    /**
     * Upload source as a tar or tar.gz and commit it. This is the main way to push code. Send the archive as the raw request body (`--data-binary @-`), or as `multipart/form-data` with a `file` field. `?message=` sets the commit message; `?parent=<sha>` commits onto a chosen commit instead of the current tip; `?branch=` commits to another branch (default: the app\'s active one, and a branch that does not exist yet is created — see `GET /api/v1/apps/{app}/branches`). A single wrapping directory is stripped, so `tar czf - myproject` lands with its contents at the root.
     * Upload source as a tar or tar.gz and commit it.
     */
    async uploadSource(requestParameters: UploadSourceRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<UploadSource200Response> {
        const response = await this.uploadSourceRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for uploadSourcePart without sending the request
     */
    async uploadSourcePartRequestOpts(requestParameters: UploadSourcePartRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['app'] == null) {
            throw new runtime.RequiredError(
                'app',
                'Required parameter "app" was null or undefined when calling uploadSourcePart().'
            );
        }

        if (requestParameters['upload'] == null) {
            throw new runtime.RequiredError(
                'upload',
                'Required parameter "upload" was null or undefined when calling uploadSourcePart().'
            );
        }

        if (requestParameters['index'] == null) {
            throw new runtime.RequiredError(
                'index',
                'Required parameter "index" was null or undefined when calling uploadSourcePart().'
            );
        }

        if (requestParameters['body'] == null) {
            throw new runtime.RequiredError(
                'body',
                'Required parameter "body" was null or undefined when calling uploadSourcePart().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/octet-stream';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/apps/{app}/source/uploads/{upload}/parts/{index}`;
        urlPath = urlPath.replace('{app}', encodeURIComponent(String(requestParameters['app'])));
        urlPath = urlPath.replace('{upload}', encodeURIComponent(String(requestParameters['upload'])));
        urlPath = urlPath.replace('{index}', encodeURIComponent(String(requestParameters['index'])));

        return {
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['body'] as any,
        };
    }

    /**
     * Send one part. Body is the raw bytes. `{index}` is 1-based. Parts may be sent in any order and retried.
     * Send one part.
     */
    async uploadSourcePartRaw(requestParameters: UploadSourcePartRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<UploadSourcePart200Response>> {
        const requestOptions = await this.uploadSourcePartRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => UploadSourcePart200ResponseFromJSON(jsonValue));
    }

    /**
     * Send one part. Body is the raw bytes. `{index}` is 1-based. Parts may be sent in any order and retried.
     * Send one part.
     */
    async uploadSourcePart(requestParameters: UploadSourcePartRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<UploadSourcePart200Response> {
        const response = await this.uploadSourcePartRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
