/* tslint:disable */
/* eslint-disable */
/**
 * AppLab API
 * AppLab deploys an application to Kubernetes by uploading its source.  Every JSON route answers inside a `{\"data\": ...}` envelope, except `/health`; failures answer `{\"error\": \"...\", \"retryable\": bool}`. Three routes answer `text/plain` and may stream (`x-streaming`), which a client must read incrementally rather than buffer.  This document is generated from AppLab\'s route table. Do not edit it by hand — run `make gen-openapi`.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AppResources
 */
export interface AppResources {
    /**
     * 
     */
    cpuLimit: string;
    /**
     * 
     */
    cpuRequest: string;
    /**
     * 
     */
    memoryLimit: string;
    /**
     * 
     */
    memoryRequest: string;
}

/**
 * Check if a given object implements the AppResources interface.
 */
export function instanceOfAppResources(value: object): value is AppResources {
    if ((!('cpuLimit' in (value as Record<string, any>)) && !('cpu_limit' in (value as Record<string, any>))) || ((value as Record<string, any>)['cpuLimit'] === undefined && (value as Record<string, any>)['cpu_limit'] === undefined)) return false;
    if ((!('cpuRequest' in (value as Record<string, any>)) && !('cpu_request' in (value as Record<string, any>))) || ((value as Record<string, any>)['cpuRequest'] === undefined && (value as Record<string, any>)['cpu_request'] === undefined)) return false;
    if ((!('memoryLimit' in (value as Record<string, any>)) && !('memory_limit' in (value as Record<string, any>))) || ((value as Record<string, any>)['memoryLimit'] === undefined && (value as Record<string, any>)['memory_limit'] === undefined)) return false;
    if ((!('memoryRequest' in (value as Record<string, any>)) && !('memory_request' in (value as Record<string, any>))) || ((value as Record<string, any>)['memoryRequest'] === undefined && (value as Record<string, any>)['memory_request'] === undefined)) return false;
    return true;
}

export function AppResourcesFromJSON(json: any): AppResources {
    return AppResourcesFromJSONTyped(json, false);
}

export function AppResourcesFromJSONTyped(json: any, ignoreDiscriminator: boolean): AppResources {
    if (json == null) {
        return json;
    }
    return {
        
        'cpuLimit': json['cpu_limit'],
        'cpuRequest': json['cpu_request'],
        'memoryLimit': json['memory_limit'],
        'memoryRequest': json['memory_request'],
    };
}

export function AppResourcesToJSON(json: any): AppResources {
    return AppResourcesToJSONTyped(json, false);
}

export function AppResourcesToJSONTyped(value?: AppResources | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'cpu_limit': value['cpuLimit'],
        'cpu_request': value['cpuRequest'],
        'memory_limit': value['memoryLimit'],
        'memory_request': value['memoryRequest'],
    };
}

