/* tslint:disable */
/* eslint-disable */
/**
 * AppLab API
 * AppLab deploys an application to Kubernetes by uploading its source.  Every JSON route answers inside a `{\"data\": ...}` envelope, except `/health`; failures answer `{\"error\": \"...\", \"retryable\": bool}`. Three routes answer `text/plain` and may stream (`x-streaming`), which a client must read incrementally rather than buffer.  This document is generated from AppLab\'s route table. Do not edit it by hand — run `make gen-openapi`.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Branches
 */
export interface Branches {
    /**
     * 
     */
    active: string;
    /**
     * 
     */
    appId: string;
    /**
     * 
     */
    branches: Array<string>;
}

/**
 * Check if a given object implements the Branches interface.
 */
export function instanceOfBranches(value: object): value is Branches {
    if (!('active' in value) || value['active'] === undefined) return false;
    if ((!('appId' in (value as Record<string, any>)) && !('app_id' in (value as Record<string, any>))) || ((value as Record<string, any>)['appId'] === undefined && (value as Record<string, any>)['app_id'] === undefined)) return false;
    if (!('branches' in value) || value['branches'] === undefined) return false;
    return true;
}

export function BranchesFromJSON(json: any): Branches {
    return BranchesFromJSONTyped(json, false);
}

export function BranchesFromJSONTyped(json: any, ignoreDiscriminator: boolean): Branches {
    if (json == null) {
        return json;
    }
    return {
        
        'active': json['active'],
        'appId': json['app_id'],
        'branches': json['branches'],
    };
}

export function BranchesToJSON(json: any): Branches {
    return BranchesToJSONTyped(json, false);
}

export function BranchesToJSONTyped(value?: Branches | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'active': value['active'],
        'app_id': value['appId'],
        'branches': value['branches'],
    };
}

