/* tslint:disable */
/* eslint-disable */
/**
 * AppLab API
 * AppLab deploys an application to Kubernetes by uploading its source.  Every JSON route answers inside a `{\"data\": ...}` envelope, except `/health`; failures answer `{\"error\": \"...\", \"retryable\": bool}`. Three routes answer `text/plain` and may stream (`x-streaming`), which a client must read incrementally rather than buffer.  This document is generated from AppLab\'s route table. Do not edit it by hand — run `make gen-openapi`.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Commit } from './Commit';
import {
    CommitFromJSON,
    CommitFromJSONTyped,
    CommitToJSON,
    CommitToJSONTyped,
} from './Commit';

/**
 * 
 * @export
 * @interface CommitList
 */
export interface CommitList {
    /**
     * 
     */
    commits: Array<Commit>;
    /**
     * 
     */
    count: number;
    /**
     * 
     */
    head: string;
}

/**
 * Check if a given object implements the CommitList interface.
 */
export function instanceOfCommitList(value: object): value is CommitList {
    if (!('commits' in value) || value['commits'] === undefined) return false;
    if (!('count' in value) || value['count'] === undefined) return false;
    if (!('head' in value) || value['head'] === undefined) return false;
    return true;
}

export function CommitListFromJSON(json: any): CommitList {
    return CommitListFromJSONTyped(json, false);
}

export function CommitListFromJSONTyped(json: any, ignoreDiscriminator: boolean): CommitList {
    if (json == null) {
        return json;
    }
    return {
        
        'commits': ((json['commits'] as Array<any>).map(CommitFromJSON)),
        'count': json['count'],
        'head': json['head'],
    };
}

export function CommitListToJSON(json: any): CommitList {
    return CommitListToJSONTyped(json, false);
}

export function CommitListToJSONTyped(value?: CommitList | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'commits': ((value['commits'] as Array<any>).map(CommitToJSON)),
        'count': value['count'],
        'head': value['head'],
    };
}

