/* tslint:disable */
/* eslint-disable */
/**
 * AppLab API
 * AppLab deploys an application to Kubernetes by uploading its source.  Every JSON route answers inside a `{\"data\": ...}` envelope, except `/health`; failures answer `{\"error\": \"...\", \"retryable\": bool}`. Three routes answer `text/plain` and may stream (`x-streaming`), which a client must read incrementally rather than buffer.  This document is generated from AppLab\'s route table. Do not edit it by hand — run `make gen-openapi`.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ListApps200ResponseDataInner } from './ListApps200ResponseDataInner';
import {
    ListApps200ResponseDataInnerFromJSON,
    ListApps200ResponseDataInnerFromJSONTyped,
    ListApps200ResponseDataInnerToJSON,
    ListApps200ResponseDataInnerToJSONTyped,
} from './ListApps200ResponseDataInner';

/**
 * 
 * @export
 * @interface CreateApp201Response
 */
export interface CreateApp201Response {
    /**
     * 
     */
    data: ListApps200ResponseDataInner;
}

/**
 * Check if a given object implements the CreateApp201Response interface.
 */
export function instanceOfCreateApp201Response(value: object): value is CreateApp201Response {
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function CreateApp201ResponseFromJSON(json: any): CreateApp201Response {
    return CreateApp201ResponseFromJSONTyped(json, false);
}

export function CreateApp201ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateApp201Response {
    if (json == null) {
        return json;
    }
    return {
        
        'data': ListApps200ResponseDataInnerFromJSON(json['data']),
    };
}

export function CreateApp201ResponseToJSON(json: any): CreateApp201Response {
    return CreateApp201ResponseToJSONTyped(json, false);
}

export function CreateApp201ResponseToJSONTyped(value?: CreateApp201Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': ListApps200ResponseDataInnerToJSON(value['data']),
    };
}

