/* tslint:disable */
/* eslint-disable */
/**
 * AppLab API
 * AppLab deploys an application to Kubernetes by uploading its source.  Every JSON route answers inside a `{\"data\": ...}` envelope, except `/health`; failures answer `{\"error\": \"...\", \"retryable\": bool}`. Three routes answer `text/plain` and may stream (`x-streaming`), which a client must read incrementally rather than buffer.  This document is generated from AppLab\'s route table. Do not edit it by hand — run `make gen-openapi`.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateAppRequest
 */
export interface CreateAppRequest {
    /**
     * 
     */
    autoDeploy?: boolean;
    /**
     * 
     */
    dockerfile?: string;
    /**
     * 
     */
    domain?: string;
    /**
     * 
     */
    id: string;
    /**
     * 
     */
    name?: string;
    /**
     * 
     */
    port?: number;
    /**
     * 
     */
    replicas?: number;
}

/**
 * Check if a given object implements the CreateAppRequest interface.
 */
export function instanceOfCreateAppRequest(value: object): value is CreateAppRequest {
    if (!('id' in value) || value['id'] === undefined) return false;
    return true;
}

export function CreateAppRequestFromJSON(json: any): CreateAppRequest {
    return CreateAppRequestFromJSONTyped(json, false);
}

export function CreateAppRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateAppRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'autoDeploy': json['auto_deploy'] == null ? undefined : json['auto_deploy'],
        'dockerfile': json['dockerfile'] == null ? undefined : json['dockerfile'],
        'domain': json['domain'] == null ? undefined : json['domain'],
        'id': json['id'],
        'name': json['name'] == null ? undefined : json['name'],
        'port': json['port'] == null ? undefined : json['port'],
        'replicas': json['replicas'] == null ? undefined : json['replicas'],
    };
}

export function CreateAppRequestToJSON(json: any): CreateAppRequest {
    return CreateAppRequestToJSONTyped(json, false);
}

export function CreateAppRequestToJSONTyped(value?: CreateAppRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'auto_deploy': value['autoDeploy'],
        'dockerfile': value['dockerfile'],
        'domain': value['domain'],
        'id': value['id'],
        'name': value['name'],
        'port': value['port'],
        'replicas': value['replicas'],
    };
}

