/* tslint:disable */
/* eslint-disable */
/**
 * AppLab API
 * AppLab deploys an application to Kubernetes by uploading its source.  Every JSON route answers inside a `{\"data\": ...}` envelope, except `/health`; failures answer `{\"error\": \"...\", \"retryable\": bool}`. Three routes answer `text/plain` and may stream (`x-streaming`), which a client must read incrementally rather than buffer.  This document is generated from AppLab\'s route table. Do not edit it by hand — run `make gen-openapi`.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DeleteApp200ResponseData
 */
export interface DeleteApp200ResponseData {
    /**
     * 
     */
    deleted?: boolean;
    /**
     * 
     */
    id?: string;
    /**
     * 
     */
    keepSource?: boolean;
}

/**
 * Check if a given object implements the DeleteApp200ResponseData interface.
 */
export function instanceOfDeleteApp200ResponseData(value: object): value is DeleteApp200ResponseData {
    return true;
}

export function DeleteApp200ResponseDataFromJSON(json: any): DeleteApp200ResponseData {
    return DeleteApp200ResponseDataFromJSONTyped(json, false);
}

export function DeleteApp200ResponseDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): DeleteApp200ResponseData {
    if (json == null) {
        return json;
    }
    return {
        
        'deleted': json['deleted'] == null ? undefined : json['deleted'],
        'id': json['id'] == null ? undefined : json['id'],
        'keepSource': json['keep_source'] == null ? undefined : json['keep_source'],
    };
}

export function DeleteApp200ResponseDataToJSON(json: any): DeleteApp200ResponseData {
    return DeleteApp200ResponseDataToJSONTyped(json, false);
}

export function DeleteApp200ResponseDataToJSONTyped(value?: DeleteApp200ResponseData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'deleted': value['deleted'],
        'id': value['id'],
        'keep_source': value['keepSource'],
    };
}

