/* tslint:disable */
/* eslint-disable */
/**
 * AppLab API
 * AppLab deploys an application to Kubernetes by uploading its source.  Every JSON route answers inside a `{\"data\": ...}` envelope, except `/health`; failures answer `{\"error\": \"...\", \"retryable\": bool}`. Three routes answer `text/plain` and may stream (`x-streaming`), which a client must read incrementally rather than buffer.  This document is generated from AppLab\'s route table. Do not edit it by hand — run `make gen-openapi`.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { App } from './App';
import {
    AppFromJSON,
    AppFromJSONTyped,
    AppToJSON,
    AppToJSONTyped,
} from './App';
import type { Build } from './Build';
import {
    BuildFromJSON,
    BuildFromJSONTyped,
    BuildToJSON,
    BuildToJSONTyped,
} from './Build';

/**
 * 
 * @export
 * @interface DeployResult
 */
export interface DeployResult {
    /**
     * 
     */
    app: App;
    /**
     * 
     */
    build: Build;
    /**
     * 
     */
    commit: string;
    /**
     * 
     */
    image: string;
    /**
     * 
     */
    url: string;
}

/**
 * Check if a given object implements the DeployResult interface.
 */
export function instanceOfDeployResult(value: object): value is DeployResult {
    if (!('app' in value) || value['app'] === undefined) return false;
    if (!('build' in value) || value['build'] === undefined) return false;
    if (!('commit' in value) || value['commit'] === undefined) return false;
    if (!('image' in value) || value['image'] === undefined) return false;
    if (!('url' in value) || value['url'] === undefined) return false;
    return true;
}

export function DeployResultFromJSON(json: any): DeployResult {
    return DeployResultFromJSONTyped(json, false);
}

export function DeployResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): DeployResult {
    if (json == null) {
        return json;
    }
    return {
        
        'app': AppFromJSON(json['app']),
        'build': BuildFromJSON(json['build']),
        'commit': json['commit'],
        'image': json['image'],
        'url': json['url'],
    };
}

export function DeployResultToJSON(json: any): DeployResult {
    return DeployResultToJSONTyped(json, false);
}

export function DeployResultToJSONTyped(value?: DeployResult | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'app': AppToJSON(value['app']),
        'build': BuildToJSON(value['build']),
        'commit': value['commit'],
        'image': value['image'],
        'url': value['url'],
    };
}

