/* tslint:disable */
/* eslint-disable */
/**
 * AppLab API
 * AppLab deploys an application to Kubernetes by uploading its source.  Every JSON route answers inside a `{\"data\": ...}` envelope, except `/health`; failures answer `{\"error\": \"...\", \"retryable\": bool}`. Three routes answer `text/plain` and may stream (`x-streaming`), which a client must read incrementally rather than buffer.  This document is generated from AppLab\'s route table. Do not edit it by hand — run `make gen-openapi`.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { App } from './App';
import {
    AppFromJSON,
    AppFromJSONTyped,
    AppToJSON,
    AppToJSONTyped,
} from './App';
import type { GetDescribe200ResponseDataAccess } from './GetDescribe200ResponseDataAccess';
import {
    GetDescribe200ResponseDataAccessFromJSON,
    GetDescribe200ResponseDataAccessFromJSONTyped,
    GetDescribe200ResponseDataAccessToJSON,
    GetDescribe200ResponseDataAccessToJSONTyped,
} from './GetDescribe200ResponseDataAccess';
import type { GetDescribe200ResponseDataDeploy } from './GetDescribe200ResponseDataDeploy';
import {
    GetDescribe200ResponseDataDeployFromJSON,
    GetDescribe200ResponseDataDeployFromJSONTyped,
    GetDescribe200ResponseDataDeployToJSON,
    GetDescribe200ResponseDataDeployToJSONTyped,
} from './GetDescribe200ResponseDataDeploy';
import type { GetDescribe200ResponseDataHowTo } from './GetDescribe200ResponseDataHowTo';
import {
    GetDescribe200ResponseDataHowToFromJSON,
    GetDescribe200ResponseDataHowToFromJSONTyped,
    GetDescribe200ResponseDataHowToToJSON,
    GetDescribe200ResponseDataHowToToJSONTyped,
} from './GetDescribe200ResponseDataHowTo';
import type { Config } from './Config';
import {
    ConfigFromJSON,
    ConfigFromJSONTyped,
    ConfigToJSON,
    ConfigToJSONTyped,
} from './Config';
import type { GetDescribe200ResponseDataBuild } from './GetDescribe200ResponseDataBuild';
import {
    GetDescribe200ResponseDataBuildFromJSON,
    GetDescribe200ResponseDataBuildFromJSONTyped,
    GetDescribe200ResponseDataBuildToJSON,
    GetDescribe200ResponseDataBuildToJSONTyped,
} from './GetDescribe200ResponseDataBuild';
import type { DescribeAPI } from './DescribeAPI';
import {
    DescribeAPIFromJSON,
    DescribeAPIFromJSONTyped,
    DescribeAPIToJSON,
    DescribeAPIToJSONTyped,
} from './DescribeAPI';

/**
 * 
 * @export
 * @interface DescribeResponse
 */
export interface DescribeResponse {
    /**
     * 
     */
    access?: GetDescribe200ResponseDataAccess;
    /**
     * 
     */
    api?: DescribeAPI;
    /**
     * 
     */
    apps?: Array<App>;
    /**
     * 
     */
    build?: GetDescribe200ResponseDataBuild;
    /**
     * 
     */
    deploy?: GetDescribe200ResponseDataDeploy;
    /**
     * 
     */
    deployment?: Config;
    /**
     * 
     */
    howTo?: GetDescribe200ResponseDataHowTo;
    /**
     * 
     */
    summary?: string;
}

/**
 * Check if a given object implements the DescribeResponse interface.
 */
export function instanceOfDescribeResponse(value: object): value is DescribeResponse {
    return true;
}

export function DescribeResponseFromJSON(json: any): DescribeResponse {
    return DescribeResponseFromJSONTyped(json, false);
}

export function DescribeResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): DescribeResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'access': json['access'] == null ? undefined : GetDescribe200ResponseDataAccessFromJSON(json['access']),
        'api': json['api'] == null ? undefined : DescribeAPIFromJSON(json['api']),
        'apps': json['apps'] == null ? undefined : ((json['apps'] as Array<any>).map(AppFromJSON)),
        'build': json['build'] == null ? undefined : GetDescribe200ResponseDataBuildFromJSON(json['build']),
        'deploy': json['deploy'] == null ? undefined : GetDescribe200ResponseDataDeployFromJSON(json['deploy']),
        'deployment': json['deployment'] == null ? undefined : ConfigFromJSON(json['deployment']),
        'howTo': json['how_to'] == null ? undefined : GetDescribe200ResponseDataHowToFromJSON(json['how_to']),
        'summary': json['summary'] == null ? undefined : json['summary'],
    };
}

export function DescribeResponseToJSON(json: any): DescribeResponse {
    return DescribeResponseToJSONTyped(json, false);
}

export function DescribeResponseToJSONTyped(value?: DescribeResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'access': GetDescribe200ResponseDataAccessToJSON(value['access']),
        'api': DescribeAPIToJSON(value['api']),
        'apps': value['apps'] == null ? undefined : ((value['apps'] as Array<any>).map(AppToJSON)),
        'build': GetDescribe200ResponseDataBuildToJSON(value['build']),
        'deploy': GetDescribe200ResponseDataDeployToJSON(value['deploy']),
        'deployment': ConfigToJSON(value['deployment']),
        'how_to': GetDescribe200ResponseDataHowToToJSON(value['howTo']),
        'summary': value['summary'],
    };
}

