/* tslint:disable */
/* eslint-disable */
/**
 * AppLab API
 * AppLab deploys an application to Kubernetes by uploading its source.  Every JSON route answers inside a `{\"data\": ...}` envelope, except `/health`; failures answer `{\"error\": \"...\", \"retryable\": bool}`. Three routes answer `text/plain` and may stream (`x-streaming`), which a client must read incrementally rather than buffer.  This document is generated from AppLab\'s route table. Do not edit it by hand — run `make gen-openapi`.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Pod } from './Pod';
import {
    PodFromJSON,
    PodFromJSONTyped,
    PodToJSON,
    PodToJSONTyped,
} from './Pod';
import type { Event } from './Event';
import {
    EventFromJSON,
    EventFromJSONTyped,
    EventToJSON,
    EventToJSONTyped,
} from './Event';

/**
 * 
 * @export
 * @interface Diagnosis
 */
export interface Diagnosis {
    /**
     * 
     */
    appId: string;
    /**
     * 
     */
    error: string;
    /**
     * 
     */
    events: Array<Event>;
    /**
     * 
     */
    logs: string;
    /**
     * 
     */
    message: string;
    /**
     * 
     */
    next: string;
    /**
     * 
     */
    pods: Array<Pod>;
    /**
     * 
     */
    previousLogs: string;
    /**
     * 
     */
    problem: string;
    /**
     * 
     */
    status: string;
    /**
     * 
     */
    statusReason: string;
}

/**
 * Check if a given object implements the Diagnosis interface.
 */
export function instanceOfDiagnosis(value: object): value is Diagnosis {
    if ((!('appId' in (value as Record<string, any>)) && !('app_id' in (value as Record<string, any>))) || ((value as Record<string, any>)['appId'] === undefined && (value as Record<string, any>)['app_id'] === undefined)) return false;
    if (!('error' in value) || value['error'] === undefined) return false;
    if (!('events' in value) || value['events'] === undefined) return false;
    if (!('logs' in value) || value['logs'] === undefined) return false;
    if (!('message' in value) || value['message'] === undefined) return false;
    if (!('next' in value) || value['next'] === undefined) return false;
    if (!('pods' in value) || value['pods'] === undefined) return false;
    if ((!('previousLogs' in (value as Record<string, any>)) && !('previous_logs' in (value as Record<string, any>))) || ((value as Record<string, any>)['previousLogs'] === undefined && (value as Record<string, any>)['previous_logs'] === undefined)) return false;
    if (!('problem' in value) || value['problem'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if ((!('statusReason' in (value as Record<string, any>)) && !('status_reason' in (value as Record<string, any>))) || ((value as Record<string, any>)['statusReason'] === undefined && (value as Record<string, any>)['status_reason'] === undefined)) return false;
    return true;
}

export function DiagnosisFromJSON(json: any): Diagnosis {
    return DiagnosisFromJSONTyped(json, false);
}

export function DiagnosisFromJSONTyped(json: any, ignoreDiscriminator: boolean): Diagnosis {
    if (json == null) {
        return json;
    }
    return {
        
        'appId': json['app_id'],
        'error': json['error'],
        'events': ((json['events'] as Array<any>).map(EventFromJSON)),
        'logs': json['logs'],
        'message': json['message'],
        'next': json['next'],
        'pods': ((json['pods'] as Array<any>).map(PodFromJSON)),
        'previousLogs': json['previous_logs'],
        'problem': json['problem'],
        'status': json['status'],
        'statusReason': json['status_reason'],
    };
}

export function DiagnosisToJSON(json: any): Diagnosis {
    return DiagnosisToJSONTyped(json, false);
}

export function DiagnosisToJSONTyped(value?: Diagnosis | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'app_id': value['appId'],
        'error': value['error'],
        'events': ((value['events'] as Array<any>).map(EventToJSON)),
        'logs': value['logs'],
        'message': value['message'],
        'next': value['next'],
        'pods': ((value['pods'] as Array<any>).map(PodToJSON)),
        'previous_logs': value['previousLogs'],
        'problem': value['problem'],
        'status': value['status'],
        'status_reason': value['statusReason'],
    };
}

