/* tslint:disable */
/* eslint-disable */
/**
 * AppLab API
 * AppLab deploys an application to Kubernetes by uploading its source.  Every JSON route answers inside a `{\"data\": ...}` envelope, except `/health`; failures answer `{\"error\": \"...\", \"retryable\": bool}`. Three routes answer `text/plain` and may stream (`x-streaming`), which a client must read incrementally rather than buffer.  This document is generated from AppLab\'s route table. Do not edit it by hand — run `make gen-openapi`.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues, parseDate, parseDateTime, serializeDate, serializeDateTime } from '../runtime';
/**
 * 
 * @export
 * @interface Event
 */
export interface Event {
    /**
     * 
     */
    count: number;
    /**
     * 
     */
    firstSeen: Date;
    /**
     * 
     */
    lastSeen: Date;
    /**
     * 
     */
    message: string;
    /**
     * 
     */
    object: string;
    /**
     * 
     */
    reason: string;
    /**
     * 
     */
    type: string;
}

/**
 * Check if a given object implements the Event interface.
 */
export function instanceOfEvent(value: object): value is Event {
    if (!('count' in value) || value['count'] === undefined) return false;
    if ((!('firstSeen' in (value as Record<string, any>)) && !('first_seen' in (value as Record<string, any>))) || ((value as Record<string, any>)['firstSeen'] === undefined && (value as Record<string, any>)['first_seen'] === undefined)) return false;
    if ((!('lastSeen' in (value as Record<string, any>)) && !('last_seen' in (value as Record<string, any>))) || ((value as Record<string, any>)['lastSeen'] === undefined && (value as Record<string, any>)['last_seen'] === undefined)) return false;
    if (!('message' in value) || value['message'] === undefined) return false;
    if (!('object' in value) || value['object'] === undefined) return false;
    if (!('reason' in value) || value['reason'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    return true;
}

export function EventFromJSON(json: any): Event {
    return EventFromJSONTyped(json, false);
}

export function EventFromJSONTyped(json: any, ignoreDiscriminator: boolean): Event {
    if (json == null) {
        return json;
    }
    return {
        
        'count': json['count'],
        'firstSeen': (json['first_seen'] == null ? json['first_seen'] : parseDateTime(json['first_seen'])),
        'lastSeen': (json['last_seen'] == null ? json['last_seen'] : parseDateTime(json['last_seen'])),
        'message': json['message'],
        'object': json['object'],
        'reason': json['reason'],
        'type': json['type'],
    };
}

export function EventToJSON(json: any): Event {
    return EventToJSONTyped(json, false);
}

export function EventToJSONTyped(value?: Event | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'count': value['count'],
        'first_seen': value['firstSeen'] == null ? value['firstSeen'] : serializeDateTime(value['firstSeen']),
        'last_seen': value['lastSeen'] == null ? value['lastSeen'] : serializeDateTime(value['lastSeen']),
        'message': value['message'],
        'object': value['object'],
        'reason': value['reason'],
        'type': value['type'],
    };
}

