/* tslint:disable */
/* eslint-disable */
/**
 * AppLab API
 * AppLab deploys an application to Kubernetes by uploading its source.  Every JSON route answers inside a `{\"data\": ...}` envelope, except `/health`; failures answer `{\"error\": \"...\", \"retryable\": bool}`. Three routes answer `text/plain` and may stream (`x-streaming`), which a client must read incrementally rather than buffer.  This document is generated from AppLab\'s route table. Do not edit it by hand — run `make gen-openapi`.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetAppStatus200ResponseData
 */
export interface GetAppStatus200ResponseData {
    /**
     * 
     */
    appId: string;
    /**
     * 
     */
    live: object;
    /**
     * 
     */
    status: string;
    /**
     * 
     */
    url: string;
}

/**
 * Check if a given object implements the GetAppStatus200ResponseData interface.
 */
export function instanceOfGetAppStatus200ResponseData(value: object): value is GetAppStatus200ResponseData {
    if ((!('appId' in (value as Record<string, any>)) && !('app_id' in (value as Record<string, any>))) || ((value as Record<string, any>)['appId'] === undefined && (value as Record<string, any>)['app_id'] === undefined)) return false;
    if (!('live' in value) || value['live'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('url' in value) || value['url'] === undefined) return false;
    return true;
}

export function GetAppStatus200ResponseDataFromJSON(json: any): GetAppStatus200ResponseData {
    return GetAppStatus200ResponseDataFromJSONTyped(json, false);
}

export function GetAppStatus200ResponseDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetAppStatus200ResponseData {
    if (json == null) {
        return json;
    }
    return {
        
        'appId': json['app_id'],
        'live': json['live'],
        'status': json['status'],
        'url': json['url'],
    };
}

export function GetAppStatus200ResponseDataToJSON(json: any): GetAppStatus200ResponseData {
    return GetAppStatus200ResponseDataToJSONTyped(json, false);
}

export function GetAppStatus200ResponseDataToJSONTyped(value?: GetAppStatus200ResponseData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'app_id': value['appId'],
        'live': value['live'],
        'status': value['status'],
        'url': value['url'],
    };
}

