/* tslint:disable */
/* eslint-disable */
/**
 * AppLab API
 * AppLab deploys an application to Kubernetes by uploading its source.  Every JSON route answers inside a `{\"data\": ...}` envelope, except `/health`; failures answer `{\"error\": \"...\", \"retryable\": bool}`. Three routes answer `text/plain` and may stream (`x-streaming`), which a client must read incrementally rather than buffer.  This document is generated from AppLab\'s route table. Do not edit it by hand — run `make gen-openapi`.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetAppConfig200ResponseData
 */
export interface GetAppConfig200ResponseData {
    /**
     * 
     */
    appId: string;
    /**
     * 
     */
    env: { [key: string]: string; };
    /**
     * 
     */
    secrets: Array<string>;
}

/**
 * Check if a given object implements the GetAppConfig200ResponseData interface.
 */
export function instanceOfGetAppConfig200ResponseData(value: object): value is GetAppConfig200ResponseData {
    if ((!('appId' in (value as Record<string, any>)) && !('app_id' in (value as Record<string, any>))) || ((value as Record<string, any>)['appId'] === undefined && (value as Record<string, any>)['app_id'] === undefined)) return false;
    if (!('env' in value) || value['env'] === undefined) return false;
    if (!('secrets' in value) || value['secrets'] === undefined) return false;
    return true;
}

export function GetAppConfig200ResponseDataFromJSON(json: any): GetAppConfig200ResponseData {
    return GetAppConfig200ResponseDataFromJSONTyped(json, false);
}

export function GetAppConfig200ResponseDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetAppConfig200ResponseData {
    if (json == null) {
        return json;
    }
    return {
        
        'appId': json['app_id'],
        'env': json['env'],
        'secrets': json['secrets'],
    };
}

export function GetAppConfig200ResponseDataToJSON(json: any): GetAppConfig200ResponseData {
    return GetAppConfig200ResponseDataToJSONTyped(json, false);
}

export function GetAppConfig200ResponseDataToJSONTyped(value?: GetAppConfig200ResponseData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'app_id': value['appId'],
        'env': value['env'],
        'secrets': value['secrets'],
    };
}

