/* tslint:disable */
/* eslint-disable */
/**
 * AppLab API
 * AppLab deploys an application to Kubernetes by uploading its source.  Every JSON route answers inside a `{\"data\": ...}` envelope, except `/health`; failures answer `{\"error\": \"...\", \"retryable\": bool}`. Three routes answer `text/plain` and may stream (`x-streaming`), which a client must read incrementally rather than buffer.  This document is generated from AppLab\'s route table. Do not edit it by hand — run `make gen-openapi`.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PodUsage } from './PodUsage';
import {
    PodUsageFromJSON,
    PodUsageFromJSONTyped,
    PodUsageToJSON,
    PodUsageToJSONTyped,
} from './PodUsage';
import type { AppResources } from './AppResources';
import {
    AppResourcesFromJSON,
    AppResourcesFromJSONTyped,
    AppResourcesToJSON,
    AppResourcesToJSONTyped,
} from './AppResources';

/**
 * 
 * @export
 * @interface GetAppUsage200ResponseData
 */
export interface GetAppUsage200ResponseData {
    /**
     * 
     */
    available: boolean;
    /**
     * 
     */
    cpu: string;
    /**
     * 
     */
    limited: AppResources;
    /**
     * 
     */
    memory: string;
    /**
     * 
     */
    pods?: { [key: string]: PodUsage; };
    /**
     * 
     */
    requested: AppResources;
}

/**
 * Check if a given object implements the GetAppUsage200ResponseData interface.
 */
export function instanceOfGetAppUsage200ResponseData(value: object): value is GetAppUsage200ResponseData {
    if (!('available' in value) || value['available'] === undefined) return false;
    if (!('cpu' in value) || value['cpu'] === undefined) return false;
    if (!('limited' in value) || value['limited'] === undefined) return false;
    if (!('memory' in value) || value['memory'] === undefined) return false;
    if (!('requested' in value) || value['requested'] === undefined) return false;
    return true;
}

export function GetAppUsage200ResponseDataFromJSON(json: any): GetAppUsage200ResponseData {
    return GetAppUsage200ResponseDataFromJSONTyped(json, false);
}

export function GetAppUsage200ResponseDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetAppUsage200ResponseData {
    if (json == null) {
        return json;
    }
    return {
        
        'available': json['available'],
        'cpu': json['cpu'],
        'limited': AppResourcesFromJSON(json['limited']),
        'memory': json['memory'],
        'pods': json['pods'] == null ? undefined : (mapValues(json['pods'], PodUsageFromJSON)),
        'requested': AppResourcesFromJSON(json['requested']),
    };
}

export function GetAppUsage200ResponseDataToJSON(json: any): GetAppUsage200ResponseData {
    return GetAppUsage200ResponseDataToJSONTyped(json, false);
}

export function GetAppUsage200ResponseDataToJSONTyped(value?: GetAppUsage200ResponseData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'available': value['available'],
        'cpu': value['cpu'],
        'limited': AppResourcesToJSON(value['limited']),
        'memory': value['memory'],
        'pods': value['pods'] == null ? undefined : (mapValues(value['pods'], PodUsageToJSON)),
        'requested': AppResourcesToJSON(value['requested']),
    };
}

