/* tslint:disable */
/* eslint-disable */
/**
 * AppLab API
 * AppLab deploys an application to Kubernetes by uploading its source.  Every JSON route answers inside a `{\"data\": ...}` envelope, except `/health`; failures answer `{\"error\": \"...\", \"retryable\": bool}`. Three routes answer `text/plain` and may stream (`x-streaming`), which a client must read incrementally rather than buffer.  This document is generated from AppLab\'s route table. Do not edit it by hand — run `make gen-openapi`.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GetAppConfig200ResponseData } from './GetAppConfig200ResponseData';
import {
    GetAppConfig200ResponseDataFromJSON,
    GetAppConfig200ResponseDataFromJSONTyped,
    GetAppConfig200ResponseDataToJSON,
    GetAppConfig200ResponseDataToJSONTyped,
} from './GetAppConfig200ResponseData';

/**
 * 
 * @export
 * @interface GetAppConfig200Response
 */
export interface GetAppConfig200Response {
    /**
     * 
     */
    data: GetAppConfig200ResponseData;
}

/**
 * Check if a given object implements the GetAppConfig200Response interface.
 */
export function instanceOfGetAppConfig200Response(value: object): value is GetAppConfig200Response {
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function GetAppConfig200ResponseFromJSON(json: any): GetAppConfig200Response {
    return GetAppConfig200ResponseFromJSONTyped(json, false);
}

export function GetAppConfig200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetAppConfig200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'data': GetAppConfig200ResponseDataFromJSON(json['data']),
    };
}

export function GetAppConfig200ResponseToJSON(json: any): GetAppConfig200Response {
    return GetAppConfig200ResponseToJSONTyped(json, false);
}

export function GetAppConfig200ResponseToJSONTyped(value?: GetAppConfig200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': GetAppConfig200ResponseDataToJSON(value['data']),
    };
}

