/* tslint:disable */
/* eslint-disable */
/**
 * AppLab API
 * AppLab deploys an application to Kubernetes by uploading its source.  Every JSON route answers inside a `{\"data\": ...}` envelope, except `/health`; failures answer `{\"error\": \"...\", \"retryable\": bool}`. Three routes answer `text/plain` and may stream (`x-streaming`), which a client must read incrementally rather than buffer.  This document is generated from AppLab\'s route table. Do not edit it by hand — run `make gen-openapi`.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GetCommit200ResponseData } from './GetCommit200ResponseData';
import {
    GetCommit200ResponseDataFromJSON,
    GetCommit200ResponseDataFromJSONTyped,
    GetCommit200ResponseDataToJSON,
    GetCommit200ResponseDataToJSONTyped,
} from './GetCommit200ResponseData';

/**
 * 
 * @export
 * @interface GetCommit200Response
 */
export interface GetCommit200Response {
    /**
     * 
     */
    data: GetCommit200ResponseData;
}

/**
 * Check if a given object implements the GetCommit200Response interface.
 */
export function instanceOfGetCommit200Response(value: object): value is GetCommit200Response {
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function GetCommit200ResponseFromJSON(json: any): GetCommit200Response {
    return GetCommit200ResponseFromJSONTyped(json, false);
}

export function GetCommit200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetCommit200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'data': GetCommit200ResponseDataFromJSON(json['data']),
    };
}

export function GetCommit200ResponseToJSON(json: any): GetCommit200Response {
    return GetCommit200ResponseToJSONTyped(json, false);
}

export function GetCommit200ResponseToJSONTyped(value?: GetCommit200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': GetCommit200ResponseDataToJSON(value['data']),
    };
}

