/* tslint:disable */
/* eslint-disable */
/**
 * AppLab API
 * AppLab deploys an application to Kubernetes by uploading its source.  Every JSON route answers inside a `{\"data\": ...}` envelope, except `/health`; failures answer `{\"error\": \"...\", \"retryable\": bool}`. Three routes answer `text/plain` and may stream (`x-streaming`), which a client must read incrementally rather than buffer.  This document is generated from AppLab\'s route table. Do not edit it by hand — run `make gen-openapi`.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetDescribe200ResponseDataBuild
 */
export interface GetDescribe200ResponseDataBuild {
    /**
     * 
     */
    enabled?: boolean;
    /**
     * 
     */
    registry?: string;
}

/**
 * Check if a given object implements the GetDescribe200ResponseDataBuild interface.
 */
export function instanceOfGetDescribe200ResponseDataBuild(value: object): value is GetDescribe200ResponseDataBuild {
    return true;
}

export function GetDescribe200ResponseDataBuildFromJSON(json: any): GetDescribe200ResponseDataBuild {
    return GetDescribe200ResponseDataBuildFromJSONTyped(json, false);
}

export function GetDescribe200ResponseDataBuildFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetDescribe200ResponseDataBuild {
    if (json == null) {
        return json;
    }
    return {
        
        'enabled': json['enabled'] == null ? undefined : json['enabled'],
        'registry': json['registry'] == null ? undefined : json['registry'],
    };
}

export function GetDescribe200ResponseDataBuildToJSON(json: any): GetDescribe200ResponseDataBuild {
    return GetDescribe200ResponseDataBuildToJSONTyped(json, false);
}

export function GetDescribe200ResponseDataBuildToJSONTyped(value?: GetDescribe200ResponseDataBuild | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'enabled': value['enabled'],
        'registry': value['registry'],
    };
}

