/* tslint:disable */
/* eslint-disable */
/**
 * AppLab API
 * AppLab deploys an application to Kubernetes by uploading its source.  Every JSON route answers inside a `{\"data\": ...}` envelope, except `/health`; failures answer `{\"error\": \"...\", \"retryable\": bool}`. Three routes answer `text/plain` and may stream (`x-streaming`), which a client must read incrementally rather than buffer.  This document is generated from AppLab\'s route table. Do not edit it by hand — run `make gen-openapi`.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetDescribe200ResponseDataAccess
 */
export interface GetDescribe200ResponseDataAccess {
    /**
     * 
     */
    app?: string;
    /**
     * 
     */
    reach?: string;
    /**
     * 
     */
    tier?: string;
}

/**
 * Check if a given object implements the GetDescribe200ResponseDataAccess interface.
 */
export function instanceOfGetDescribe200ResponseDataAccess(value: object): value is GetDescribe200ResponseDataAccess {
    return true;
}

export function GetDescribe200ResponseDataAccessFromJSON(json: any): GetDescribe200ResponseDataAccess {
    return GetDescribe200ResponseDataAccessFromJSONTyped(json, false);
}

export function GetDescribe200ResponseDataAccessFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetDescribe200ResponseDataAccess {
    if (json == null) {
        return json;
    }
    return {
        
        'app': json['app'] == null ? undefined : json['app'],
        'reach': json['reach'] == null ? undefined : json['reach'],
        'tier': json['tier'] == null ? undefined : json['tier'],
    };
}

export function GetDescribe200ResponseDataAccessToJSON(json: any): GetDescribe200ResponseDataAccess {
    return GetDescribe200ResponseDataAccessToJSONTyped(json, false);
}

export function GetDescribe200ResponseDataAccessToJSONTyped(value?: GetDescribe200ResponseDataAccess | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'app': value['app'],
        'reach': value['reach'],
        'tier': value['tier'],
    };
}

