/* tslint:disable */
/* eslint-disable */
/**
 * AppLab API
 * AppLab deploys an application to Kubernetes by uploading its source.  Every JSON route answers inside a `{\"data\": ...}` envelope, except `/health`; failures answer `{\"error\": \"...\", \"retryable\": bool}`. Three routes answer `text/plain` and may stream (`x-streaming`), which a client must read incrementally rather than buffer.  This document is generated from AppLab\'s route table. Do not edit it by hand — run `make gen-openapi`.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetDescribe200ResponseDataDeploy
 */
export interface GetDescribe200ResponseDataDeploy {
    /**
     * 
     */
    baseDomain?: string;
    /**
     * 
     */
    domainTemplate?: string;
    /**
     * 
     */
    enabled?: boolean;
    /**
     * 
     */
    gateway?: string;
    /**
     * 
     */
    pathPrefix?: string;
}

/**
 * Check if a given object implements the GetDescribe200ResponseDataDeploy interface.
 */
export function instanceOfGetDescribe200ResponseDataDeploy(value: object): value is GetDescribe200ResponseDataDeploy {
    return true;
}

export function GetDescribe200ResponseDataDeployFromJSON(json: any): GetDescribe200ResponseDataDeploy {
    return GetDescribe200ResponseDataDeployFromJSONTyped(json, false);
}

export function GetDescribe200ResponseDataDeployFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetDescribe200ResponseDataDeploy {
    if (json == null) {
        return json;
    }
    return {
        
        'baseDomain': json['base_domain'] == null ? undefined : json['base_domain'],
        'domainTemplate': json['domain_template'] == null ? undefined : json['domain_template'],
        'enabled': json['enabled'] == null ? undefined : json['enabled'],
        'gateway': json['gateway'] == null ? undefined : json['gateway'],
        'pathPrefix': json['path_prefix'] == null ? undefined : json['path_prefix'],
    };
}

export function GetDescribe200ResponseDataDeployToJSON(json: any): GetDescribe200ResponseDataDeploy {
    return GetDescribe200ResponseDataDeployToJSONTyped(json, false);
}

export function GetDescribe200ResponseDataDeployToJSONTyped(value?: GetDescribe200ResponseDataDeploy | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'base_domain': value['baseDomain'],
        'domain_template': value['domainTemplate'],
        'enabled': value['enabled'],
        'gateway': value['gateway'],
        'path_prefix': value['pathPrefix'],
    };
}

