/* tslint:disable */
/* eslint-disable */
/**
 * AppLab API
 * AppLab deploys an application to Kubernetes by uploading its source.  Every JSON route answers inside a `{\"data\": ...}` envelope, except `/health`; failures answer `{\"error\": \"...\", \"retryable\": bool}`. Three routes answer `text/plain` and may stream (`x-streaming`), which a client must read incrementally rather than buffer.  This document is generated from AppLab\'s route table. Do not edit it by hand — run `make gen-openapi`.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetVersion200ResponseData
 */
export interface GetVersion200ResponseData {
    /**
     * 
     */
    buildTime?: string;
    /**
     * 
     */
    commit?: string;
    /**
     * 
     */
    goVersion?: string;
    /**
     * 
     */
    version?: string;
}

/**
 * Check if a given object implements the GetVersion200ResponseData interface.
 */
export function instanceOfGetVersion200ResponseData(value: object): value is GetVersion200ResponseData {
    return true;
}

export function GetVersion200ResponseDataFromJSON(json: any): GetVersion200ResponseData {
    return GetVersion200ResponseDataFromJSONTyped(json, false);
}

export function GetVersion200ResponseDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetVersion200ResponseData {
    if (json == null) {
        return json;
    }
    return {
        
        'buildTime': json['build_time'] == null ? undefined : json['build_time'],
        'commit': json['commit'] == null ? undefined : json['commit'],
        'goVersion': json['go_version'] == null ? undefined : json['go_version'],
        'version': json['version'] == null ? undefined : json['version'],
    };
}

export function GetVersion200ResponseDataToJSON(json: any): GetVersion200ResponseData {
    return GetVersion200ResponseDataToJSONTyped(json, false);
}

export function GetVersion200ResponseDataToJSONTyped(value?: GetVersion200ResponseData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'build_time': value['buildTime'],
        'commit': value['commit'],
        'go_version': value['goVersion'],
        'version': value['version'],
    };
}

