/* tslint:disable */
/* eslint-disable */
/**
 * AppLab API
 * AppLab deploys an application to Kubernetes by uploading its source.  Every JSON route answers inside a `{\"data\": ...}` envelope, except `/health`; failures answer `{\"error\": \"...\", \"retryable\": bool}`. Three routes answer `text/plain` and may stream (`x-streaming`), which a client must read incrementally rather than buffer.  This document is generated from AppLab\'s route table. Do not edit it by hand — run `make gen-openapi`.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GetVersion200ResponseData } from './GetVersion200ResponseData';
import {
    GetVersion200ResponseDataFromJSON,
    GetVersion200ResponseDataFromJSONTyped,
    GetVersion200ResponseDataToJSON,
    GetVersion200ResponseDataToJSONTyped,
} from './GetVersion200ResponseData';

/**
 * 
 * @export
 * @interface GetVersion200Response
 */
export interface GetVersion200Response {
    /**
     * 
     */
    data: GetVersion200ResponseData;
}

/**
 * Check if a given object implements the GetVersion200Response interface.
 */
export function instanceOfGetVersion200Response(value: object): value is GetVersion200Response {
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function GetVersion200ResponseFromJSON(json: any): GetVersion200Response {
    return GetVersion200ResponseFromJSONTyped(json, false);
}

export function GetVersion200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetVersion200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'data': GetVersion200ResponseDataFromJSON(json['data']),
    };
}

export function GetVersion200ResponseToJSON(json: any): GetVersion200Response {
    return GetVersion200ResponseToJSONTyped(json, false);
}

export function GetVersion200ResponseToJSONTyped(value?: GetVersion200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': GetVersion200ResponseDataToJSON(value['data']),
    };
}

