/* tslint:disable */
/* eslint-disable */
/**
 * AppLab API
 * AppLab deploys an application to Kubernetes by uploading its source.  Every JSON route answers inside a `{\"data\": ...}` envelope, except `/health`; failures answer `{\"error\": \"...\", \"retryable\": bool}`. Three routes answer `text/plain` and may stream (`x-streaming`), which a client must read incrementally rather than buffer.  This document is generated from AppLab\'s route table. Do not edit it by hand — run `make gen-openapi`.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AgentFile } from './AgentFile';
import {
    AgentFileFromJSON,
    AgentFileFromJSONTyped,
    AgentFileToJSON,
    AgentFileToJSONTyped,
} from './AgentFile';

/**
 * 
 * @export
 * @interface ListAgentFiles200ResponseData
 */
export interface ListAgentFiles200ResponseData {
    /**
     * 
     */
    files?: Array<AgentFile>;
}

/**
 * Check if a given object implements the ListAgentFiles200ResponseData interface.
 */
export function instanceOfListAgentFiles200ResponseData(value: object): value is ListAgentFiles200ResponseData {
    return true;
}

export function ListAgentFiles200ResponseDataFromJSON(json: any): ListAgentFiles200ResponseData {
    return ListAgentFiles200ResponseDataFromJSONTyped(json, false);
}

export function ListAgentFiles200ResponseDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListAgentFiles200ResponseData {
    if (json == null) {
        return json;
    }
    return {
        
        'files': json['files'] == null ? undefined : ((json['files'] as Array<any>).map(AgentFileFromJSON)),
    };
}

export function ListAgentFiles200ResponseDataToJSON(json: any): ListAgentFiles200ResponseData {
    return ListAgentFiles200ResponseDataToJSONTyped(json, false);
}

export function ListAgentFiles200ResponseDataToJSONTyped(value?: ListAgentFiles200ResponseData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'files': value['files'] == null ? undefined : ((value['files'] as Array<any>).map(AgentFileToJSON)),
    };
}

