/* tslint:disable */
/* eslint-disable */
/**
 * AppLab API
 * AppLab deploys an application to Kubernetes by uploading its source.  Every JSON route answers inside a `{\"data\": ...}` envelope, except `/health`; failures answer `{\"error\": \"...\", \"retryable\": bool}`. Three routes answer `text/plain` and may stream (`x-streaming`), which a client must read incrementally rather than buffer.  This document is generated from AppLab\'s route table. Do not edit it by hand — run `make gen-openapi`.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ListCommits200ResponseData } from './ListCommits200ResponseData';
import {
    ListCommits200ResponseDataFromJSON,
    ListCommits200ResponseDataFromJSONTyped,
    ListCommits200ResponseDataToJSON,
    ListCommits200ResponseDataToJSONTyped,
} from './ListCommits200ResponseData';

/**
 * 
 * @export
 * @interface ListCommits200Response
 */
export interface ListCommits200Response {
    /**
     * 
     */
    data: ListCommits200ResponseData;
}

/**
 * Check if a given object implements the ListCommits200Response interface.
 */
export function instanceOfListCommits200Response(value: object): value is ListCommits200Response {
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function ListCommits200ResponseFromJSON(json: any): ListCommits200Response {
    return ListCommits200ResponseFromJSONTyped(json, false);
}

export function ListCommits200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListCommits200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'data': ListCommits200ResponseDataFromJSON(json['data']),
    };
}

export function ListCommits200ResponseToJSON(json: any): ListCommits200Response {
    return ListCommits200ResponseToJSONTyped(json, false);
}

export function ListCommits200ResponseToJSONTyped(value?: ListCommits200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': ListCommits200ResponseDataToJSON(value['data']),
    };
}

