/* tslint:disable */
/* eslint-disable */
/**
 * AppLab API
 * AppLab deploys an application to Kubernetes by uploading its source.  Every JSON route answers inside a `{\"data\": ...}` envelope, except `/health`; failures answer `{\"error\": \"...\", \"retryable\": bool}`. Three routes answer `text/plain` and may stream (`x-streaming`), which a client must read incrementally rather than buffer.  This document is generated from AppLab\'s route table. Do not edit it by hand — run `make gen-openapi`.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Pod } from './Pod';
import {
    PodFromJSON,
    PodFromJSONTyped,
    PodToJSON,
    PodToJSONTyped,
} from './Pod';

/**
 * 
 * @export
 * @interface ListAppPods200ResponseData
 */
export interface ListAppPods200ResponseData {
    /**
     * 
     */
    appId: string;
    /**
     * 
     */
    count: number;
    /**
     * 
     */
    pods: Array<Pod>;
}

/**
 * Check if a given object implements the ListAppPods200ResponseData interface.
 */
export function instanceOfListAppPods200ResponseData(value: object): value is ListAppPods200ResponseData {
    if ((!('appId' in (value as Record<string, any>)) && !('app_id' in (value as Record<string, any>))) || ((value as Record<string, any>)['appId'] === undefined && (value as Record<string, any>)['app_id'] === undefined)) return false;
    if (!('count' in value) || value['count'] === undefined) return false;
    if (!('pods' in value) || value['pods'] === undefined) return false;
    return true;
}

export function ListAppPods200ResponseDataFromJSON(json: any): ListAppPods200ResponseData {
    return ListAppPods200ResponseDataFromJSONTyped(json, false);
}

export function ListAppPods200ResponseDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListAppPods200ResponseData {
    if (json == null) {
        return json;
    }
    return {
        
        'appId': json['app_id'],
        'count': json['count'],
        'pods': ((json['pods'] as Array<any>).map(PodFromJSON)),
    };
}

export function ListAppPods200ResponseDataToJSON(json: any): ListAppPods200ResponseData {
    return ListAppPods200ResponseDataToJSONTyped(json, false);
}

export function ListAppPods200ResponseDataToJSONTyped(value?: ListAppPods200ResponseData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'app_id': value['appId'],
        'count': value['count'],
        'pods': ((value['pods'] as Array<any>).map(PodToJSON)),
    };
}

