/* tslint:disable */
/* eslint-disable */
/**
 * AppLab API
 * AppLab deploys an application to Kubernetes by uploading its source.  Every JSON route answers inside a `{\"data\": ...}` envelope, except `/health`; failures answer `{\"error\": \"...\", \"retryable\": bool}`. Three routes answer `text/plain` and may stream (`x-streaming`), which a client must read incrementally rather than buffer.  This document is generated from AppLab\'s route table. Do not edit it by hand — run `make gen-openapi`.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues, parseDate, parseDateTime, serializeDate, serializeDateTime } from '../runtime';
import type { AppResources } from './AppResources';
import {
    AppResourcesFromJSON,
    AppResourcesFromJSONTyped,
    AppResourcesToJSON,
    AppResourcesToJSONTyped,
} from './AppResources';

/**
 * 
 * @export
 * @interface ListApps200ResponseDataInner
 */
export interface ListApps200ResponseDataInner {
    /**
     * 
     */
    appKey: string;
    /**
     * 
     */
    autoDeploy: boolean;
    /**
     * 
     */
    branch: string;
    /**
     * 
     */
    buildStatus: string;
    /**
     * 
     */
    commitSha: string;
    /**
     * 
     */
    createdAt: Date;
    /**
     * 
     */
    dockerfile: string;
    /**
     * 
     */
    domain: string;
    /**
     * 
     */
    envCount: number;
    /**
     * 
     */
    gitUrl: string;
    /**
     * 
     */
    gitUrlWithKey: string;
    /**
     * 
     */
    id: string;
    /**
     * 
     */
    image: string;
    /**
     * 
     */
    name: string;
    /**
     * 
     */
    port: number;
    /**
     * 
     */
    replicas: number;
    /**
     * 
     */
    resources: AppResources;
    /**
     * 
     */
    runStatus: string;
    /**
     * 
     */
    status: string;
    /**
     * 
     */
    statusReason: string;
    /**
     * 
     */
    updatedAt: Date;
    /**
     * 
     */
    url: string;
}

/**
 * Check if a given object implements the ListApps200ResponseDataInner interface.
 */
export function instanceOfListApps200ResponseDataInner(value: object): value is ListApps200ResponseDataInner {
    if ((!('appKey' in (value as Record<string, any>)) && !('app_key' in (value as Record<string, any>))) || ((value as Record<string, any>)['appKey'] === undefined && (value as Record<string, any>)['app_key'] === undefined)) return false;
    if ((!('autoDeploy' in (value as Record<string, any>)) && !('auto_deploy' in (value as Record<string, any>))) || ((value as Record<string, any>)['autoDeploy'] === undefined && (value as Record<string, any>)['auto_deploy'] === undefined)) return false;
    if (!('branch' in value) || value['branch'] === undefined) return false;
    if ((!('buildStatus' in (value as Record<string, any>)) && !('build_status' in (value as Record<string, any>))) || ((value as Record<string, any>)['buildStatus'] === undefined && (value as Record<string, any>)['build_status'] === undefined)) return false;
    if ((!('commitSha' in (value as Record<string, any>)) && !('commit_sha' in (value as Record<string, any>))) || ((value as Record<string, any>)['commitSha'] === undefined && (value as Record<string, any>)['commit_sha'] === undefined)) return false;
    if ((!('createdAt' in (value as Record<string, any>)) && !('created_at' in (value as Record<string, any>))) || ((value as Record<string, any>)['createdAt'] === undefined && (value as Record<string, any>)['created_at'] === undefined)) return false;
    if (!('dockerfile' in value) || value['dockerfile'] === undefined) return false;
    if (!('domain' in value) || value['domain'] === undefined) return false;
    if ((!('envCount' in (value as Record<string, any>)) && !('env_count' in (value as Record<string, any>))) || ((value as Record<string, any>)['envCount'] === undefined && (value as Record<string, any>)['env_count'] === undefined)) return false;
    if ((!('gitUrl' in (value as Record<string, any>)) && !('git_url' in (value as Record<string, any>))) || ((value as Record<string, any>)['gitUrl'] === undefined && (value as Record<string, any>)['git_url'] === undefined)) return false;
    if ((!('gitUrlWithKey' in (value as Record<string, any>)) && !('git_url_with_key' in (value as Record<string, any>))) || ((value as Record<string, any>)['gitUrlWithKey'] === undefined && (value as Record<string, any>)['git_url_with_key'] === undefined)) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('image' in value) || value['image'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('port' in value) || value['port'] === undefined) return false;
    if (!('replicas' in value) || value['replicas'] === undefined) return false;
    if (!('resources' in value) || value['resources'] === undefined) return false;
    if ((!('runStatus' in (value as Record<string, any>)) && !('run_status' in (value as Record<string, any>))) || ((value as Record<string, any>)['runStatus'] === undefined && (value as Record<string, any>)['run_status'] === undefined)) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if ((!('statusReason' in (value as Record<string, any>)) && !('status_reason' in (value as Record<string, any>))) || ((value as Record<string, any>)['statusReason'] === undefined && (value as Record<string, any>)['status_reason'] === undefined)) return false;
    if ((!('updatedAt' in (value as Record<string, any>)) && !('updated_at' in (value as Record<string, any>))) || ((value as Record<string, any>)['updatedAt'] === undefined && (value as Record<string, any>)['updated_at'] === undefined)) return false;
    if (!('url' in value) || value['url'] === undefined) return false;
    return true;
}

export function ListApps200ResponseDataInnerFromJSON(json: any): ListApps200ResponseDataInner {
    return ListApps200ResponseDataInnerFromJSONTyped(json, false);
}

export function ListApps200ResponseDataInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListApps200ResponseDataInner {
    if (json == null) {
        return json;
    }
    return {
        
        'appKey': json['app_key'],
        'autoDeploy': json['auto_deploy'],
        'branch': json['branch'],
        'buildStatus': json['build_status'],
        'commitSha': json['commit_sha'],
        'createdAt': (json['created_at'] == null ? json['created_at'] : parseDateTime(json['created_at'])),
        'dockerfile': json['dockerfile'],
        'domain': json['domain'],
        'envCount': json['env_count'],
        'gitUrl': json['git_url'],
        'gitUrlWithKey': json['git_url_with_key'],
        'id': json['id'],
        'image': json['image'],
        'name': json['name'],
        'port': json['port'],
        'replicas': json['replicas'],
        'resources': AppResourcesFromJSON(json['resources']),
        'runStatus': json['run_status'],
        'status': json['status'],
        'statusReason': json['status_reason'],
        'updatedAt': (json['updated_at'] == null ? json['updated_at'] : parseDateTime(json['updated_at'])),
        'url': json['url'],
    };
}

export function ListApps200ResponseDataInnerToJSON(json: any): ListApps200ResponseDataInner {
    return ListApps200ResponseDataInnerToJSONTyped(json, false);
}

export function ListApps200ResponseDataInnerToJSONTyped(value?: ListApps200ResponseDataInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'app_key': value['appKey'],
        'auto_deploy': value['autoDeploy'],
        'branch': value['branch'],
        'build_status': value['buildStatus'],
        'commit_sha': value['commitSha'],
        'created_at': value['createdAt'] == null ? value['createdAt'] : serializeDateTime(value['createdAt']),
        'dockerfile': value['dockerfile'],
        'domain': value['domain'],
        'env_count': value['envCount'],
        'git_url': value['gitUrl'],
        'git_url_with_key': value['gitUrlWithKey'],
        'id': value['id'],
        'image': value['image'],
        'name': value['name'],
        'port': value['port'],
        'replicas': value['replicas'],
        'resources': AppResourcesToJSON(value['resources']),
        'run_status': value['runStatus'],
        'status': value['status'],
        'status_reason': value['statusReason'],
        'updated_at': value['updatedAt'] == null ? value['updatedAt'] : serializeDateTime(value['updatedAt']),
        'url': value['url'],
    };
}

