/* tslint:disable */
/* eslint-disable */
/**
 * AppLab API
 * AppLab deploys an application to Kubernetes by uploading its source.  Every JSON route answers inside a `{\"data\": ...}` envelope, except `/health`; failures answer `{\"error\": \"...\", \"retryable\": bool}`. Three routes answer `text/plain` and may stream (`x-streaming`), which a client must read incrementally rather than buffer.  This document is generated from AppLab\'s route table. Do not edit it by hand — run `make gen-openapi`.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ListServers200ResponseDataInner } from './ListServers200ResponseDataInner';
import {
    ListServers200ResponseDataInnerFromJSON,
    ListServers200ResponseDataInnerFromJSONTyped,
    ListServers200ResponseDataInnerToJSON,
    ListServers200ResponseDataInnerToJSONTyped,
} from './ListServers200ResponseDataInner';

/**
 * 
 * @export
 * @interface ListServers200Response
 */
export interface ListServers200Response {
    /**
     * 
     */
    data: Array<ListServers200ResponseDataInner>;
}

/**
 * Check if a given object implements the ListServers200Response interface.
 */
export function instanceOfListServers200Response(value: object): value is ListServers200Response {
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function ListServers200ResponseFromJSON(json: any): ListServers200Response {
    return ListServers200ResponseFromJSONTyped(json, false);
}

export function ListServers200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListServers200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'data': ((json['data'] as Array<any>).map(ListServers200ResponseDataInnerFromJSON)),
    };
}

export function ListServers200ResponseToJSON(json: any): ListServers200Response {
    return ListServers200ResponseToJSONTyped(json, false);
}

export function ListServers200ResponseToJSONTyped(value?: ListServers200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': ((value['data'] as Array<any>).map(ListServers200ResponseDataInnerToJSON)),
    };
}

