/* tslint:disable */
/* eslint-disable */
/**
 * AppLab API
 * AppLab deploys an application to Kubernetes by uploading its source.  Every JSON route answers inside a `{\"data\": ...}` envelope, except `/health`; failures answer `{\"error\": \"...\", \"retryable\": bool}`. Three routes answer `text/plain` and may stream (`x-streaming`), which a client must read incrementally rather than buffer.  This document is generated from AppLab\'s route table. Do not edit it by hand — run `make gen-openapi`.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ListAgentFiles200ResponseData } from './ListAgentFiles200ResponseData';
import {
    ListAgentFiles200ResponseDataFromJSON,
    ListAgentFiles200ResponseDataFromJSONTyped,
    ListAgentFiles200ResponseDataToJSON,
    ListAgentFiles200ResponseDataToJSONTyped,
} from './ListAgentFiles200ResponseData';

/**
 * 
 * @export
 * @interface ListAgentFiles200Response
 */
export interface ListAgentFiles200Response {
    /**
     * 
     */
    data: ListAgentFiles200ResponseData;
}

/**
 * Check if a given object implements the ListAgentFiles200Response interface.
 */
export function instanceOfListAgentFiles200Response(value: object): value is ListAgentFiles200Response {
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function ListAgentFiles200ResponseFromJSON(json: any): ListAgentFiles200Response {
    return ListAgentFiles200ResponseFromJSONTyped(json, false);
}

export function ListAgentFiles200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListAgentFiles200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'data': ListAgentFiles200ResponseDataFromJSON(json['data']),
    };
}

export function ListAgentFiles200ResponseToJSON(json: any): ListAgentFiles200Response {
    return ListAgentFiles200ResponseToJSONTyped(json, false);
}

export function ListAgentFiles200ResponseToJSONTyped(value?: ListAgentFiles200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': ListAgentFiles200ResponseDataToJSON(value['data']),
    };
}

