/* tslint:disable */
/* eslint-disable */
/**
 * AppLab API
 * AppLab deploys an application to Kubernetes by uploading its source.  Every JSON route answers inside a `{\"data\": ...}` envelope, except `/health`; failures answer `{\"error\": \"...\", \"retryable\": bool}`. Three routes answer `text/plain` and may stream (`x-streaming`), which a client must read incrementally rather than buffer.  This document is generated from AppLab\'s route table. Do not edit it by hand — run `make gen-openapi`.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { OverviewBuilds } from './OverviewBuilds';
import {
    OverviewBuildsFromJSON,
    OverviewBuildsFromJSONTyped,
    OverviewBuildsToJSON,
    OverviewBuildsToJSONTyped,
} from './OverviewBuilds';
import type { OverviewApps } from './OverviewApps';
import {
    OverviewAppsFromJSON,
    OverviewAppsFromJSONTyped,
    OverviewAppsToJSON,
    OverviewAppsToJSONTyped,
} from './OverviewApps';
import type { Config } from './Config';
import {
    ConfigFromJSON,
    ConfigFromJSONTyped,
    ConfigToJSON,
    ConfigToJSONTyped,
} from './Config';
import type { OverviewCluster } from './OverviewCluster';
import {
    OverviewClusterFromJSON,
    OverviewClusterFromJSONTyped,
    OverviewClusterToJSON,
    OverviewClusterToJSONTyped,
} from './OverviewCluster';

/**
 * 
 * @export
 * @interface Overview
 */
export interface Overview {
    /**
     * 
     */
    apps: OverviewApps;
    /**
     * 
     */
    builds: OverviewBuilds;
    /**
     * 
     */
    cluster: OverviewCluster;
    /**
     * 
     */
    deployment: Config;
}

/**
 * Check if a given object implements the Overview interface.
 */
export function instanceOfOverview(value: object): value is Overview {
    if (!('apps' in value) || value['apps'] === undefined) return false;
    if (!('builds' in value) || value['builds'] === undefined) return false;
    if (!('cluster' in value) || value['cluster'] === undefined) return false;
    if (!('deployment' in value) || value['deployment'] === undefined) return false;
    return true;
}

export function OverviewFromJSON(json: any): Overview {
    return OverviewFromJSONTyped(json, false);
}

export function OverviewFromJSONTyped(json: any, ignoreDiscriminator: boolean): Overview {
    if (json == null) {
        return json;
    }
    return {
        
        'apps': OverviewAppsFromJSON(json['apps']),
        'builds': OverviewBuildsFromJSON(json['builds']),
        'cluster': OverviewClusterFromJSON(json['cluster']),
        'deployment': ConfigFromJSON(json['deployment']),
    };
}

export function OverviewToJSON(json: any): Overview {
    return OverviewToJSONTyped(json, false);
}

export function OverviewToJSONTyped(value?: Overview | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'apps': OverviewAppsToJSON(value['apps']),
        'builds': OverviewBuildsToJSON(value['builds']),
        'cluster': OverviewClusterToJSON(value['cluster']),
        'deployment': ConfigToJSON(value['deployment']),
    };
}

