/* tslint:disable */
/* eslint-disable */
/**
 * AppLab API
 * AppLab deploys an application to Kubernetes by uploading its source.  Every JSON route answers inside a `{\"data\": ...}` envelope, except `/health`; failures answer `{\"error\": \"...\", \"retryable\": bool}`. Three routes answer `text/plain` and may stream (`x-streaming`), which a client must read incrementally rather than buffer.  This document is generated from AppLab\'s route table. Do not edit it by hand — run `make gen-openapi`.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface OverviewApps
 */
export interface OverviewApps {
    /**
     * 
     */
    buildFailed: number;
    /**
     * 
     */
    building: number;
    /**
     * 
     */
    created: number;
    /**
     * 
     */
    deploying: number;
    /**
     * 
     */
    failed: number;
    /**
     * 
     */
    needsAttention: number;
    /**
     * 
     */
    running: number;
    /**
     * 
     */
    total: number;
}

/**
 * Check if a given object implements the OverviewApps interface.
 */
export function instanceOfOverviewApps(value: object): value is OverviewApps {
    if ((!('buildFailed' in (value as Record<string, any>)) && !('build_failed' in (value as Record<string, any>))) || ((value as Record<string, any>)['buildFailed'] === undefined && (value as Record<string, any>)['build_failed'] === undefined)) return false;
    if (!('building' in value) || value['building'] === undefined) return false;
    if (!('created' in value) || value['created'] === undefined) return false;
    if (!('deploying' in value) || value['deploying'] === undefined) return false;
    if (!('failed' in value) || value['failed'] === undefined) return false;
    if ((!('needsAttention' in (value as Record<string, any>)) && !('needs_attention' in (value as Record<string, any>))) || ((value as Record<string, any>)['needsAttention'] === undefined && (value as Record<string, any>)['needs_attention'] === undefined)) return false;
    if (!('running' in value) || value['running'] === undefined) return false;
    if (!('total' in value) || value['total'] === undefined) return false;
    return true;
}

export function OverviewAppsFromJSON(json: any): OverviewApps {
    return OverviewAppsFromJSONTyped(json, false);
}

export function OverviewAppsFromJSONTyped(json: any, ignoreDiscriminator: boolean): OverviewApps {
    if (json == null) {
        return json;
    }
    return {
        
        'buildFailed': json['build_failed'],
        'building': json['building'],
        'created': json['created'],
        'deploying': json['deploying'],
        'failed': json['failed'],
        'needsAttention': json['needs_attention'],
        'running': json['running'],
        'total': json['total'],
    };
}

export function OverviewAppsToJSON(json: any): OverviewApps {
    return OverviewAppsToJSONTyped(json, false);
}

export function OverviewAppsToJSONTyped(value?: OverviewApps | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'build_failed': value['buildFailed'],
        'building': value['building'],
        'created': value['created'],
        'deploying': value['deploying'],
        'failed': value['failed'],
        'needs_attention': value['needsAttention'],
        'running': value['running'],
        'total': value['total'],
    };
}

