/* tslint:disable */
/* eslint-disable */
/**
 * AppLab API
 * AppLab deploys an application to Kubernetes by uploading its source.  Every JSON route answers inside a `{\"data\": ...}` envelope, except `/health`; failures answer `{\"error\": \"...\", \"retryable\": bool}`. Three routes answer `text/plain` and may stream (`x-streaming`), which a client must read incrementally rather than buffer.  This document is generated from AppLab\'s route table. Do not edit it by hand — run `make gen-openapi`.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface OverviewCluster
 */
export interface OverviewCluster {
    /**
     * 
     */
    configured: boolean;
    /**
     * 
     */
    reachable: boolean;
}

/**
 * Check if a given object implements the OverviewCluster interface.
 */
export function instanceOfOverviewCluster(value: object): value is OverviewCluster {
    if (!('configured' in value) || value['configured'] === undefined) return false;
    if (!('reachable' in value) || value['reachable'] === undefined) return false;
    return true;
}

export function OverviewClusterFromJSON(json: any): OverviewCluster {
    return OverviewClusterFromJSONTyped(json, false);
}

export function OverviewClusterFromJSONTyped(json: any, ignoreDiscriminator: boolean): OverviewCluster {
    if (json == null) {
        return json;
    }
    return {
        
        'configured': json['configured'],
        'reachable': json['reachable'],
    };
}

export function OverviewClusterToJSON(json: any): OverviewCluster {
    return OverviewClusterToJSONTyped(json, false);
}

export function OverviewClusterToJSONTyped(value?: OverviewCluster | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'configured': value['configured'],
        'reachable': value['reachable'],
    };
}

