/* tslint:disable */
/* eslint-disable */
/**
 * AppLab API
 * AppLab deploys an application to Kubernetes by uploading its source.  Every JSON route answers inside a `{\"data\": ...}` envelope, except `/health`; failures answer `{\"error\": \"...\", \"retryable\": bool}`. Three routes answer `text/plain` and may stream (`x-streaming`), which a client must read incrementally rather than buffer.  This document is generated from AppLab\'s route table. Do not edit it by hand — run `make gen-openapi`.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Pod
 */
export interface Pod {
    /**
     * 
     */
    containers: Array<object>;
    /**
     * 
     */
    image: string;
    /**
     * 
     */
    labels: { [key: string]: string; };
    /**
     * 
     */
    message: string;
    /**
     * 
     */
    name: string;
    /**
     * 
     */
    phase: string;
    /**
     * 
     */
    ready: boolean;
    /**
     * 
     */
    reason: string;
    /**
     * 
     */
    restarts: number;
}

/**
 * Check if a given object implements the Pod interface.
 */
export function instanceOfPod(value: object): value is Pod {
    if (!('containers' in value) || value['containers'] === undefined) return false;
    if (!('image' in value) || value['image'] === undefined) return false;
    if (!('labels' in value) || value['labels'] === undefined) return false;
    if (!('message' in value) || value['message'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('phase' in value) || value['phase'] === undefined) return false;
    if (!('ready' in value) || value['ready'] === undefined) return false;
    if (!('reason' in value) || value['reason'] === undefined) return false;
    if (!('restarts' in value) || value['restarts'] === undefined) return false;
    return true;
}

export function PodFromJSON(json: any): Pod {
    return PodFromJSONTyped(json, false);
}

export function PodFromJSONTyped(json: any, ignoreDiscriminator: boolean): Pod {
    if (json == null) {
        return json;
    }
    return {
        
        'containers': json['containers'],
        'image': json['image'],
        'labels': json['labels'],
        'message': json['message'],
        'name': json['name'],
        'phase': json['phase'],
        'ready': json['ready'],
        'reason': json['reason'],
        'restarts': json['restarts'],
    };
}

export function PodToJSON(json: any): Pod {
    return PodToJSONTyped(json, false);
}

export function PodToJSONTyped(value?: Pod | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'containers': value['containers'],
        'image': value['image'],
        'labels': value['labels'],
        'message': value['message'],
        'name': value['name'],
        'phase': value['phase'],
        'ready': value['ready'],
        'reason': value['reason'],
        'restarts': value['restarts'],
    };
}

