/* tslint:disable */
/* eslint-disable */
/**
 * AppLab API
 * AppLab deploys an application to Kubernetes by uploading its source.  Every JSON route answers inside a `{\"data\": ...}` envelope, except `/health`; failures answer `{\"error\": \"...\", \"retryable\": bool}`. Three routes answer `text/plain` and may stream (`x-streaming`), which a client must read incrementally rather than buffer.  This document is generated from AppLab\'s route table. Do not edit it by hand — run `make gen-openapi`.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ListServers200ResponseDataInner } from './ListServers200ResponseDataInner';
import {
    ListServers200ResponseDataInnerFromJSON,
    ListServers200ResponseDataInnerFromJSONTyped,
    ListServers200ResponseDataInnerToJSON,
    ListServers200ResponseDataInnerToJSONTyped,
} from './ListServers200ResponseDataInner';

/**
 * 
 * @export
 * @interface RegisterServer201Response
 */
export interface RegisterServer201Response {
    /**
     * 
     */
    data: ListServers200ResponseDataInner;
}

/**
 * Check if a given object implements the RegisterServer201Response interface.
 */
export function instanceOfRegisterServer201Response(value: object): value is RegisterServer201Response {
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function RegisterServer201ResponseFromJSON(json: any): RegisterServer201Response {
    return RegisterServer201ResponseFromJSONTyped(json, false);
}

export function RegisterServer201ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): RegisterServer201Response {
    if (json == null) {
        return json;
    }
    return {
        
        'data': ListServers200ResponseDataInnerFromJSON(json['data']),
    };
}

export function RegisterServer201ResponseToJSON(json: any): RegisterServer201Response {
    return RegisterServer201ResponseToJSONTyped(json, false);
}

export function RegisterServer201ResponseToJSONTyped(value?: RegisterServer201Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': ListServers200ResponseDataInnerToJSON(value['data']),
    };
}

