/* tslint:disable */
/* eslint-disable */
/**
 * AppLab API
 * AppLab deploys an application to Kubernetes by uploading its source.  Every JSON route answers inside a `{\"data\": ...}` envelope, except `/health`; failures answer `{\"error\": \"...\", \"retryable\": bool}`. Three routes answer `text/plain` and may stream (`x-streaming`), which a client must read incrementally rather than buffer.  This document is generated from AppLab\'s route table. Do not edit it by hand — run `make gen-openapi`.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RemoveServer200ResponseData
 */
export interface RemoveServer200ResponseData {
    /**
     * 
     */
    id?: string;
    /**
     * 
     */
    removed?: boolean;
}

/**
 * Check if a given object implements the RemoveServer200ResponseData interface.
 */
export function instanceOfRemoveServer200ResponseData(value: object): value is RemoveServer200ResponseData {
    return true;
}

export function RemoveServer200ResponseDataFromJSON(json: any): RemoveServer200ResponseData {
    return RemoveServer200ResponseDataFromJSONTyped(json, false);
}

export function RemoveServer200ResponseDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): RemoveServer200ResponseData {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'removed': json['removed'] == null ? undefined : json['removed'],
    };
}

export function RemoveServer200ResponseDataToJSON(json: any): RemoveServer200ResponseData {
    return RemoveServer200ResponseDataToJSONTyped(json, false);
}

export function RemoveServer200ResponseDataToJSONTyped(value?: RemoveServer200ResponseData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'removed': value['removed'],
    };
}

