/* tslint:disable */
/* eslint-disable */
/**
 * AppLab API
 * AppLab deploys an application to Kubernetes by uploading its source.  Every JSON route answers inside a `{\"data\": ...}` envelope, except `/health`; failures answer `{\"error\": \"...\", \"retryable\": bool}`. Three routes answer `text/plain` and may stream (`x-streaming`), which a client must read incrementally rather than buffer.  This document is generated from AppLab\'s route table. Do not edit it by hand — run `make gen-openapi`.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { RemoveServer200ResponseData } from './RemoveServer200ResponseData';
import {
    RemoveServer200ResponseDataFromJSON,
    RemoveServer200ResponseDataFromJSONTyped,
    RemoveServer200ResponseDataToJSON,
    RemoveServer200ResponseDataToJSONTyped,
} from './RemoveServer200ResponseData';

/**
 * 
 * @export
 * @interface RemoveServer200Response
 */
export interface RemoveServer200Response {
    /**
     * 
     */
    data: RemoveServer200ResponseData;
}

/**
 * Check if a given object implements the RemoveServer200Response interface.
 */
export function instanceOfRemoveServer200Response(value: object): value is RemoveServer200Response {
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function RemoveServer200ResponseFromJSON(json: any): RemoveServer200Response {
    return RemoveServer200ResponseFromJSONTyped(json, false);
}

export function RemoveServer200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): RemoveServer200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'data': RemoveServer200ResponseDataFromJSON(json['data']),
    };
}

export function RemoveServer200ResponseToJSON(json: any): RemoveServer200Response {
    return RemoveServer200ResponseToJSONTyped(json, false);
}

export function RemoveServer200ResponseToJSONTyped(value?: RemoveServer200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': RemoveServer200ResponseDataToJSON(value['data']),
    };
}

