/* tslint:disable */
/* eslint-disable */
/**
 * AppLab API
 * AppLab deploys an application to Kubernetes by uploading its source.  Every JSON route answers inside a `{\"data\": ...}` envelope, except `/health`; failures answer `{\"error\": \"...\", \"retryable\": bool}`. Three routes answer `text/plain` and may stream (`x-streaming`), which a client must read incrementally rather than buffer.  This document is generated from AppLab\'s route table. Do not edit it by hand — run `make gen-openapi`.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RestartResponse
 */
export interface RestartResponse {
    /**
     * 
     */
    app?: string;
    /**
     * 
     */
    restarted?: boolean;
}

/**
 * Check if a given object implements the RestartResponse interface.
 */
export function instanceOfRestartResponse(value: object): value is RestartResponse {
    return true;
}

export function RestartResponseFromJSON(json: any): RestartResponse {
    return RestartResponseFromJSONTyped(json, false);
}

export function RestartResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): RestartResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'app': json['app'] == null ? undefined : json['app'],
        'restarted': json['restarted'] == null ? undefined : json['restarted'],
    };
}

export function RestartResponseToJSON(json: any): RestartResponse {
    return RestartResponseToJSONTyped(json, false);
}

export function RestartResponseToJSONTyped(value?: RestartResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'app': value['app'],
        'restarted': value['restarted'],
    };
}

