/* tslint:disable */
/* eslint-disable */
/**
 * AppLab API
 * AppLab deploys an application to Kubernetes by uploading its source.  Every JSON route answers inside a `{\"data\": ...}` envelope, except `/health`; failures answer `{\"error\": \"...\", \"retryable\": bool}`. Three routes answer `text/plain` and may stream (`x-streaming`), which a client must read incrementally rather than buffer.  This document is generated from AppLab\'s route table. Do not edit it by hand — run `make gen-openapi`.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SetEnvRequest
 */
export interface SetEnvRequest {
    /**
     * 
     */
    env: { [key: string]: string; };
}

/**
 * Check if a given object implements the SetEnvRequest interface.
 */
export function instanceOfSetEnvRequest(value: object): value is SetEnvRequest {
    if (!('env' in value) || value['env'] === undefined) return false;
    return true;
}

export function SetEnvRequestFromJSON(json: any): SetEnvRequest {
    return SetEnvRequestFromJSONTyped(json, false);
}

export function SetEnvRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): SetEnvRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'env': json['env'],
    };
}

export function SetEnvRequestToJSON(json: any): SetEnvRequest {
    return SetEnvRequestToJSONTyped(json, false);
}

export function SetEnvRequestToJSONTyped(value?: SetEnvRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'env': value['env'],
    };
}

