/* tslint:disable */
/* eslint-disable */
/**
 * AppLab API
 * AppLab deploys an application to Kubernetes by uploading its source.  Every JSON route answers inside a `{\"data\": ...}` envelope, except `/health`; failures answer `{\"error\": \"...\", \"retryable\": bool}`. Three routes answer `text/plain` and may stream (`x-streaming`), which a client must read incrementally rather than buffer.  This document is generated from AppLab\'s route table. Do not edit it by hand — run `make gen-openapi`.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { StartChunkedUpload201ResponseData } from './StartChunkedUpload201ResponseData';
import {
    StartChunkedUpload201ResponseDataFromJSON,
    StartChunkedUpload201ResponseDataFromJSONTyped,
    StartChunkedUpload201ResponseDataToJSON,
    StartChunkedUpload201ResponseDataToJSONTyped,
} from './StartChunkedUpload201ResponseData';

/**
 * 
 * @export
 * @interface StartChunkedUpload201Response
 */
export interface StartChunkedUpload201Response {
    /**
     * 
     */
    data: StartChunkedUpload201ResponseData;
}

/**
 * Check if a given object implements the StartChunkedUpload201Response interface.
 */
export function instanceOfStartChunkedUpload201Response(value: object): value is StartChunkedUpload201Response {
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function StartChunkedUpload201ResponseFromJSON(json: any): StartChunkedUpload201Response {
    return StartChunkedUpload201ResponseFromJSONTyped(json, false);
}

export function StartChunkedUpload201ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): StartChunkedUpload201Response {
    if (json == null) {
        return json;
    }
    return {
        
        'data': StartChunkedUpload201ResponseDataFromJSON(json['data']),
    };
}

export function StartChunkedUpload201ResponseToJSON(json: any): StartChunkedUpload201Response {
    return StartChunkedUpload201ResponseToJSONTyped(json, false);
}

export function StartChunkedUpload201ResponseToJSONTyped(value?: StartChunkedUpload201Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': StartChunkedUpload201ResponseDataToJSON(value['data']),
    };
}

