/* tslint:disable */
/* eslint-disable */
/**
 * AppLab API
 * AppLab deploys an application to Kubernetes by uploading its source.  Every JSON route answers inside a `{\"data\": ...}` envelope, except `/health`; failures answer `{\"error\": \"...\", \"retryable\": bool}`. Three routes answer `text/plain` and may stream (`x-streaming`), which a client must read incrementally rather than buffer.  This document is generated from AppLab\'s route table. Do not edit it by hand — run `make gen-openapi`.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { App } from './App';
import {
    AppFromJSON,
    AppFromJSONTyped,
    AppToJSON,
    AppToJSONTyped,
} from './App';

/**
 * 
 * @export
 * @interface StopResponse
 */
export interface StopResponse {
    /**
     * 
     */
    app?: App;
    /**
     * 
     */
    stopped?: boolean;
}

/**
 * Check if a given object implements the StopResponse interface.
 */
export function instanceOfStopResponse(value: object): value is StopResponse {
    return true;
}

export function StopResponseFromJSON(json: any): StopResponse {
    return StopResponseFromJSONTyped(json, false);
}

export function StopResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): StopResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'app': json['app'] == null ? undefined : AppFromJSON(json['app']),
        'stopped': json['stopped'] == null ? undefined : json['stopped'],
    };
}

export function StopResponseToJSON(json: any): StopResponse {
    return StopResponseToJSONTyped(json, false);
}

export function StopResponseToJSONTyped(value?: StopResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'app': AppToJSON(value['app']),
        'stopped': value['stopped'],
    };
}

