/* tslint:disable */
/* eslint-disable */
/**
 * AppLab API
 * AppLab deploys an application to Kubernetes by uploading its source.  Every JSON route answers inside a `{\"data\": ...}` envelope, except `/health`; failures answer `{\"error\": \"...\", \"retryable\": bool}`. Three routes answer `text/plain` and may stream (`x-streaming`), which a client must read incrementally rather than buffer.  This document is generated from AppLab\'s route table. Do not edit it by hand — run `make gen-openapi`.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SwitchBranchRequest
 */
export interface SwitchBranchRequest {
    /**
     * 
     */
    branch: string;
}

/**
 * Check if a given object implements the SwitchBranchRequest interface.
 */
export function instanceOfSwitchBranchRequest(value: object): value is SwitchBranchRequest {
    if (!('branch' in value) || value['branch'] === undefined) return false;
    return true;
}

export function SwitchBranchRequestFromJSON(json: any): SwitchBranchRequest {
    return SwitchBranchRequestFromJSONTyped(json, false);
}

export function SwitchBranchRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): SwitchBranchRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'branch': json['branch'],
    };
}

export function SwitchBranchRequestToJSON(json: any): SwitchBranchRequest {
    return SwitchBranchRequestToJSONTyped(json, false);
}

export function SwitchBranchRequestToJSONTyped(value?: SwitchBranchRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'branch': value['branch'],
    };
}

