/* tslint:disable */
/* eslint-disable */
/**
 * AppLab API
 * AppLab deploys an application to Kubernetes by uploading its source.  Every JSON route answers inside a `{\"data\": ...}` envelope, except `/health`; failures answer `{\"error\": \"...\", \"retryable\": bool}`. Three routes answer `text/plain` and may stream (`x-streaming`), which a client must read incrementally rather than buffer.  This document is generated from AppLab\'s route table. Do not edit it by hand — run `make gen-openapi`.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { UploadSourcePart200ResponseData } from './UploadSourcePart200ResponseData';
import {
    UploadSourcePart200ResponseDataFromJSON,
    UploadSourcePart200ResponseDataFromJSONTyped,
    UploadSourcePart200ResponseDataToJSON,
    UploadSourcePart200ResponseDataToJSONTyped,
} from './UploadSourcePart200ResponseData';

/**
 * 
 * @export
 * @interface UploadSourcePart200Response
 */
export interface UploadSourcePart200Response {
    /**
     * 
     */
    data: UploadSourcePart200ResponseData;
}

/**
 * Check if a given object implements the UploadSourcePart200Response interface.
 */
export function instanceOfUploadSourcePart200Response(value: object): value is UploadSourcePart200Response {
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function UploadSourcePart200ResponseFromJSON(json: any): UploadSourcePart200Response {
    return UploadSourcePart200ResponseFromJSONTyped(json, false);
}

export function UploadSourcePart200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): UploadSourcePart200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'data': UploadSourcePart200ResponseDataFromJSON(json['data']),
    };
}

export function UploadSourcePart200ResponseToJSON(json: any): UploadSourcePart200Response {
    return UploadSourcePart200ResponseToJSONTyped(json, false);
}

export function UploadSourcePart200ResponseToJSONTyped(value?: UploadSourcePart200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': UploadSourcePart200ResponseDataToJSON(value['data']),
    };
}

