/* tslint:disable */
/* eslint-disable */
/**
 * AppLab API
 * AppLab deploys an application to Kubernetes by uploading its source.  Every JSON route answers inside a `{\"data\": ...}` envelope, except `/health`; failures answer `{\"error\": \"...\", \"retryable\": bool}`. Three routes answer `text/plain` and may stream (`x-streaming`), which a client must read incrementally rather than buffer.  This document is generated from AppLab\'s route table. Do not edit it by hand — run `make gen-openapi`.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UploadSourcePart200ResponseData
 */
export interface UploadSourcePart200ResponseData {
    /**
     * 
     */
    index?: number;
    /**
     * 
     */
    size?: number;
    /**
     * 
     */
    uploadId?: string;
}

/**
 * Check if a given object implements the UploadSourcePart200ResponseData interface.
 */
export function instanceOfUploadSourcePart200ResponseData(value: object): value is UploadSourcePart200ResponseData {
    return true;
}

export function UploadSourcePart200ResponseDataFromJSON(json: any): UploadSourcePart200ResponseData {
    return UploadSourcePart200ResponseDataFromJSONTyped(json, false);
}

export function UploadSourcePart200ResponseDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): UploadSourcePart200ResponseData {
    if (json == null) {
        return json;
    }
    return {
        
        'index': json['index'] == null ? undefined : json['index'],
        'size': json['size'] == null ? undefined : json['size'],
        'uploadId': json['upload_id'] == null ? undefined : json['upload_id'],
    };
}

export function UploadSourcePart200ResponseDataToJSON(json: any): UploadSourcePart200ResponseData {
    return UploadSourcePart200ResponseDataToJSONTyped(json, false);
}

export function UploadSourcePart200ResponseDataToJSONTyped(value?: UploadSourcePart200ResponseData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'index': value['index'],
        'size': value['size'],
        'upload_id': value['uploadId'],
    };
}

