/* tslint:disable */
/* eslint-disable */
/**
 * AppLab API
 * AppLab deploys an application to Kubernetes by uploading its source.  Every JSON route answers inside a `{\"data\": ...}` envelope, except `/health`; failures answer `{\"error\": \"...\", \"retryable\": bool}`. Three routes answer `text/plain` and may stream (`x-streaming`), which a client must read incrementally rather than buffer.  This document is generated from AppLab\'s route table. Do not edit it by hand — run `make gen-openapi`.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { UploadSource200ResponseData } from './UploadSource200ResponseData';
import {
    UploadSource200ResponseDataFromJSON,
    UploadSource200ResponseDataFromJSONTyped,
    UploadSource200ResponseDataToJSON,
    UploadSource200ResponseDataToJSONTyped,
} from './UploadSource200ResponseData';

/**
 * 
 * @export
 * @interface UploadSource200Response
 */
export interface UploadSource200Response {
    /**
     * 
     */
    data: UploadSource200ResponseData;
}

/**
 * Check if a given object implements the UploadSource200Response interface.
 */
export function instanceOfUploadSource200Response(value: object): value is UploadSource200Response {
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function UploadSource200ResponseFromJSON(json: any): UploadSource200Response {
    return UploadSource200ResponseFromJSONTyped(json, false);
}

export function UploadSource200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): UploadSource200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'data': UploadSource200ResponseDataFromJSON(json['data']),
    };
}

export function UploadSource200ResponseToJSON(json: any): UploadSource200Response {
    return UploadSource200ResponseToJSONTyped(json, false);
}

export function UploadSource200ResponseToJSONTyped(value?: UploadSource200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': UploadSource200ResponseDataToJSON(value['data']),
    };
}

