// Package llms renders llms.txt — the document that tells an agent (or a
// person) how to use this deployment.
//
// It is treated as part of the API rather than as documentation about it. The
// endpoint list is generated from the same route table that configures the
// server, so a route cannot exist undocumented or be documented without
// existing; the prose around it is written here and checked against the
// committed copy in api/llms.txt by a test.
//
// Two standing rules for the content, both learned from the failure modes of
// agent-facing docs:
//
//   - Describe capability, not destruction. This file is read by agents that
//     act on what they find, so it documents the functional endpoints in enough
//     detail to call them correctly.
//   - Keep it true. A new route, a changed parameter or a changed default is a
//     change to this file in the same commit.
package llms

import (
	"strings"
)

// Render produces the full document.
//
// routeReference is generated by the API layer from its route table; passing it
// in rather than importing the API layer keeps this package free of a cycle and
// makes the document testable on its own.
func Render(routeReference string) string {
	var b strings.Builder

	b.WriteString(prologue)
	b.WriteString("\n")
	b.WriteString(concepts)
	b.WriteString("\n")
	b.WriteString(authentication)

	b.WriteString("\n## API reference\n\n")
	b.WriteString("Every route below is relative to this deployment's base URL, which\n")
	b.WriteString("`GET /api/v1/config` reports as `api_base_url`. _(`key` means the route\n")
	b.WriteString("requires `Authorization: Bearer <key>`; `no key` means it does not.)_\n\n")
	// Indented by the renderer rather than baked into each doc string, so the
	// route table's one-line descriptions stay readable at their definition.
	b.WriteString(strings.TrimRight(routeReference, "\n"))
	b.WriteString("\n")

	b.WriteString(errorsSection)

	return b.String()
}

const prologue = `# AppLab

> Deploy an application to Kubernetes by uploading its source. You get back a
> URL. There is no Dockerfile you must write by hand, no CI to configure, no
> registry to push to and no manifest to apply.

AppLab owns the whole path from a local working directory to a running
application: it stores your source in a git repository it hosts, builds an image
from it in a build Job inside the cluster, deploys that image, and exposes it on
a hostname. One HTTP call starts that path; one call streams the build log; one
call tells you what is running.

Two things are enough to use it: **the base URL** and **an API key**.

## The shape of it

    upload source ──▶ build image ──▶ deploy ──▶ https://<app>.<domain>

Each step is idempotent and observable. You can upload again to redeploy, watch
a build's log while it runs, and roll back to any earlier upload without
rebuilding it.

## Start here

    curl -sS "$APPLAB_URL/api/v1/config"

That needs no key, so it is the cheapest way to check the URL is right and to
read back this deployment's limits and its default domain. Then create an app
and push code to it — see the API reference at the end of this file.

## What applab is not

It is not a general-purpose Kubernetes client. It manages the resources of the
apps you create through it and nothing else, and it confines itself to the one
namespace it runs in. Reaching for it to inspect or change anything else will
not work.
`

const concepts = `## Concepts

### An app

An app is the unit of everything: one source repository, one image, one
Deployment, one address. Its **id** is how you refer to it everywhere, and it is
immutable — there is no rename, so nothing has to be rewritten when it changes.

An id has to survive being a URL path segment, a git repository directory and a
Kubernetes object name, so it is constrained to what is valid as all three:
lowercase letters, digits and dashes, starting with a letter or digit, at most
40 characters. Some names are reserved because they would collide with this
service's own routes.

### Source is a git repository

Every app's source lives in its own git repository, hosted here. Uploading a
tarball of your working directory writes a commit to it — the tarball is how the
bytes travel, the commit is what is recorded.

That matters because it means the source is real: you can clone it, see its
history, diff two uploads and roll back by deploying an earlier commit. If this
service were lost, the repositories would still be readable with ordinary git
tools.

Uploading a tarball rather than pushing over git is deliberate: a plain HTTP
upload works from anywhere, including from an agent or a container that has no
git credential and no way to navigate an interactive auth prompt.

### Commits are what you deploy

A deploy names a commit. Rolling back means deploying an earlier one — and if
that commit was built before, its image already exists and is reused rather than
rebuilt, so a rollback is fast and cannot fail for a reason the original build
did not.

### How an app is addressed

A deployment publishes apps one of two ways, and GET /api/v1/config reports which
via "base_domain", "path_prefix" and "domain_template". Read it rather than
assuming, because the answer changes what a URL looks like.

- **A hostname per app** (path_prefix empty): an app with id "shop" is served at
  shop.<base_domain>. Its "hostname" is "shop.<base_domain>" and its "url" adds a
  scheme.
- **One host, one path per app** (path_prefix set): every app shares
  <base_domain> and the path says which is meant, so "shop" is served at
  <base_domain><path_prefix>/shop.

Either way, an app can override its own hostname by setting "domain" when it is
created or updated, in which case it is served at that host's root.

The prefix is stripped before a request reaches the app, so an app served under a
prefix sees the same paths it would see if it were at the root. A
"X-Forwarded-Prefix" header tells it where it is mounted, which is what it needs
to build correct absolute links.

In the API, an app's "hostname" is the host and "path" the path under it — so
with a path prefix, the two together are the address and neither alone is. The
"url" field is the whole thing, scheme included, and is empty until the app has
been deployed.

### One namespace for everything

Every app is deployed into the same namespace the service itself runs in. That is
what lets it hold a namespaced Role rather than a ClusterRole — it has no
permission anywhere else in the cluster, so the blast radius of a bug here is the
apps it manages rather than every workload you run.

The trade is that a namespace no longer separates one app from another. Its
objects are told apart by an applab.io/app label, which every object it creates
carries and every query filters by. Deleting an app removes its objects and
leaves the rest alone; the pods and events endpoints report one app's workload,
not the namespace's.

GET /api/v1/config reports which namespace this is, as "namespace".

### applab's record versus the cluster

Applab keeps a record of what it last did — which commit it deployed, whether
the build succeeded — but **the cluster is the source of truth for what is
running**. When the two disagree, believe the cluster. An app reporting
"running" while its pods are crash-looping means the last thing applab recorded
was a successful rollout and something has happened since; the pod and event
endpoints are how you see that.
`

const authentication = `## Authentication

There is no user store. **An API key is the whole identity**: presenting a
configured key means you may do anything this deployment can do.

Send it on every request that needs one:

    Authorization: Bearer <key>

A bare key with no ` + "`Bearer `" + ` prefix also works, for a caller pasting one in by
hand. A key is **never** accepted as a query parameter or a form field — URLs are
written to access logs, kept in shell history and sent in Referer headers, so a
credential placed in one leaks by default.

There is one tier. A key that authenticates can also delete, so treat it the way
you would treat any credential that can destroy data.

` + "`GET /health`" + `, ` + "`GET /api/v1/config`" + ` and ` + "`GET /llms.txt`" + ` need no key, because a
liveness probe cannot hold one and a caller has to be able to find out what this
service is before it can authenticate to it. Everything else does.
`

const errorsSection = `
## Errors

Every failure is JSON with a meaningful HTTP status, never a 200 carrying a
failure:

    { "error": "human readable reason", "retryable": false }

**Branch on the HTTP status.** ` + "`retryable`" + ` is an additional signal for the cases
where a status alone is ambiguous — 409 and 503 are each sometimes worth
retrying and sometimes not, and guessing wrong means either giving up on a
transient failure or hammering a permanent one.

| Status | Meaning | What to do |
|---|---|---|
| 400 | The request is malformed | Fix the request; retrying will not help |
| 401 | Missing or unrecognised key | Check the ` + "`Authorization`" + ` header |
| 403 | Authenticated but not permitted | Nothing to retry |
| 404 | No such app, build or commit | Check the id |
| 409 | Conflicting state, or the resource already exists | Read the current state and decide |
| 413 | Body too large | Use the chunked upload endpoints |
| 500 | A bug in applab | Retry once, then report it |
| 503 | This deployment is shedding load or cannot reach the cluster | Back off briefly and retry |

A success is the payload under ` + "`data`" + `:
` + "```" + `
    { "data": { ... } }
` + "```" + `
There is no ` + "`code`" + ` or ` + "`success`" + ` field to check — a 2xx means the call worked.
`

// Committed is the checked-in copy of the rendered document, loaded by the
// api/llms.txt test. The served document is regenerated per request, so a
// stale file here cannot be served — it can only be detected.
//
// Regenerate with `make llms`.
